namespace Medcom.Contracts;

// Source-pinned read fields only. These DTOs never grant write access.
// SQL decimal values are strings; SQL datetime values have milliseconds and no inferred timezone.

public sealed record PurchaseOrderHeaderFields(
    string DocumentId,
    string DocumentDate,
    string ObjectId,
    string? Memo,
    string? Notes,
    string? DeliverDate,
    string CurrencyId,
    double RateExchange,
    string? BaseTotal,
    string? SearchField,
    bool IsLock,
    string? UserCreate,
    string? UserUpdate,
    string? DateUpdate,
    string? DateCreate,
    string? LinkId,
    string? ContractId,
    int? StatusId,
    string BranchId);

public sealed record PurchaseOrderLineFields(
    string UserAutoId,
    string DocumentId,
    string ItemId,
    string? Quantity,
    string? UnitPrice,
    string? SourceAmount,
    string? Amount,
    string? Notes,
    string? Quantity2,
    string? Property,
    string? Property2,
    string? ParentId);

public sealed record InboundRequestHeaderFields(
    string DocumentId,
    string DocumentDate,
    string OrderNumber,
    string? BranchId,
    string InvoiceNo,
    string? DeclarationNumber,
    string DeparturePoint,
    string DestinationPoint,
    bool? IsRain,
    string OrderTypeId,
    string? ObjectId,
    string? TotalPalletQuantityByDocument,
    string? TotalBarrelQuantityByDocument,
    string? TotalPalletQuantityByReal,
    string? TotalBarrelQuantityByReal,
    string? ExcessPackageQuantity,
    string? LackOfPackageQuantity,
    string? DamagedPackageQuantity,
    string? PackageTypeId,
    bool? IsDamageOutsidePackage,
    string? DamageDescription,
    string? DamageInsideStatusId,
    string? LocationDamageDetectedId,
    string? LocationDamageDescription,
    string? ResultDesciption,
    string? TotalQuantityInboundResult,
    string? GoodAwaitingInboundResult,
    string? ResultNote,
    string? DatetimeRecorded,
    int StatusId,
    string? CurrencyId,
    string? RateExchange,
    string? ImageUrl,
    string? BbkcUrl,
    string? Notes,
    string? SendTo,
    string QrPrintType);

public sealed record InboundRequestLineFields(
    string UserAutoId,
    string DocumentId,
    string? ContractId,
    string ItemId,
    string? HangSX,
    double? UnitFactor,
    string? Unit2,
    bool? Additional,
    string? LotNumberByDocument,
    string? SetQuantityByDocument,
    string? BarrelQuantityByDocument,
    string? ExpireDateByDocument,
    string? LotNumberByReal,
    string? SetQuantityByReal,
    string? BarrelQuantityByReal,
    string? ExpireDateByReal,
    string? SourceAmount,
    string? UnitPrice,
    string? Amount,
    string? RandomTestQuantity,
    string? TestStatus,
    string? NoPalletNote,
    string? PalletNote,
    string? CheckerNote,
    string? ItemCode);

public sealed record PurchaseRequestHeaderFields(
    string PurchaseRequestId,
    string? PurchaseDate,
    int? PurposeId,
    string PersonSuggest,
    string Department,
    string? PurposeDescOrClient,
    string? Price,
    string? Notes,
    int StatusId,
    bool? IsLock,
    string CurrencyId,
    string ObjectId,
    double RateExchange,
    string BranchId);

public sealed record PurchaseRequestLineFields(
    string UserAutoId,
    string ItemId,
    string? Budget,
    string? TimeRequired,
    string Quantity,
    string UnitPrice,
    string? TotalPrice,
    string? Model,
    string? PurchaseRequestId);

public sealed record PurchaseRequestSourceFields(PurchaseRequestHeaderFields Header,
    IReadOnlyList<PurchaseRequestLineFields> Lines);
