// Generated by tools/source/generate_erp_screen_contracts.py from sanitized current-form metadata.
// Fixed inputs only: document IDs, actors, branches, locks, workflow and calculated fields are server-owned.
using System.Text.Json.Serialization;
namespace Medcom.Contracts;

[JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Disallow)]
public sealed record ErpPurchaseRequestHeaderInput
{
    [JsonPropertyName("purchaseDate")]
    public string? PurchaseDate { get; init; }
    [JsonPropertyName("purposeId")]
    public int? PurposeId { get; init; }
    [JsonPropertyName("personSuggest")]
    public required string PersonSuggest { get; init; }
    [JsonPropertyName("department")]
    public required string Department { get; init; }
    [JsonPropertyName("purposeDescOrClient")]
    public string? PurposeDescOrClient { get; init; }
    [JsonPropertyName("price")]
    public string? Price { get; init; }
    [JsonPropertyName("notes")]
    public string? Notes { get; init; }
    [JsonPropertyName("currencyId")]
    public required string CurrencyId { get; init; }
    [JsonPropertyName("objectId")]
    public required string ObjectId { get; init; }
    [JsonPropertyName("rateExchange")]
    public required double RateExchange { get; init; }
}

[JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Disallow)]
public sealed record ErpPurchaseRequestLineInput
{
    [JsonPropertyName("itemId")]
    public required string ItemId { get; init; }
    [JsonPropertyName("budget")]
    public string? Budget { get; init; }
    [JsonPropertyName("timeRequired")]
    public string? TimeRequired { get; init; }
    [JsonPropertyName("quantity")]
    public required string Quantity { get; init; }
    [JsonPropertyName("unitPrice")]
    public required string UnitPrice { get; init; }
    [JsonPropertyName("model")]
    public string? Model { get; init; }
}

[JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Disallow)]
public sealed record ErpSalesOrderHeaderInput
{
    [JsonPropertyName("documentDate")]
    public required string DocumentDate { get; init; }
    [JsonPropertyName("objectId")]
    public required string ObjectId { get; init; }
    [JsonPropertyName("contractId")]
    public string? ContractId { get; init; }
    [JsonPropertyName("memo")]
    public string? Memo { get; init; }
    [JsonPropertyName("deliverDate")]
    public string? DeliverDate { get; init; }
    [JsonPropertyName("baseTotal")]
    public string? BaseTotal { get; init; }
    [JsonPropertyName("employeeId")]
    public required string EmployeeId { get; init; }
    [JsonPropertyName("managerId")]
    public string? ManagerId { get; init; }
    [JsonPropertyName("phone")]
    public string? Phone { get; init; }
    [JsonPropertyName("taxCode")]
    public string? TaxCode { get; init; }
    [JsonPropertyName("notes")]
    public string? Notes { get; init; }
    [JsonPropertyName("depositAmount")]
    public string? DepositAmount { get; init; }
    [JsonPropertyName("agencyId")]
    public string? AgencyId { get; init; }
    [JsonPropertyName("isVAT")]
    public bool? IsVAT { get; init; }
    [JsonPropertyName("isOrder")]
    public required bool IsOrder { get; init; }
    [JsonPropertyName("currencyId")]
    public required string CurrencyId { get; init; }
    [JsonPropertyName("rateExchange")]
    public required double RateExchange { get; init; }
    [JsonPropertyName("linkId")]
    public string? LinkId { get; init; }
    [JsonPropertyName("ghiChuDonHang")]
    public string? GhiChuDonHang { get; init; }
    [JsonPropertyName("paymentTermId")]
    public string? PaymentTermId { get; init; }
    [JsonPropertyName("ceoId")]
    public string? CeoId { get; init; }
    [JsonPropertyName("thamGiaHopDongBan")]
    public bool? ThamGiaHopDongBan { get; init; }
    [JsonPropertyName("bBKCUrl")]
    public string? BBKCUrl { get; init; }
    [JsonPropertyName("beforeOutStockUrl")]
    public string? BeforeOutStockUrl { get; init; }
    [JsonPropertyName("bBBGUrl")]
    public string? BBBGUrl { get; init; }
    [JsonPropertyName("documentUrl")]
    public string? DocumentUrl { get; init; }
    [JsonPropertyName("handoverLocation")]
    public string? HandoverLocation { get; init; }
    [JsonPropertyName("representedByA")]
    public string? RepresentedByA { get; init; }
    [JsonPropertyName("positionA")]
    public string? PositionA { get; init; }
    [JsonPropertyName("addressA")]
    public string? AddressA { get; init; }
    [JsonPropertyName("representedByB")]
    public string? RepresentedByB { get; init; }
    [JsonPropertyName("positionB")]
    public string? PositionB { get; init; }
    [JsonPropertyName("addressB")]
    public string? AddressB { get; init; }
    [JsonPropertyName("conclude")]
    public string? Conclude { get; init; }
    [JsonPropertyName("minutesNumber")]
    public int? MinutesNumber { get; init; }
    [JsonPropertyName("partyAKeep")]
    public int? PartyAKeep { get; init; }
    [JsonPropertyName("partyBKeep")]
    public int? PartyBKeep { get; init; }
    [JsonPropertyName("deliveryStatusId")]
    public int? DeliveryStatusId { get; init; }
    [JsonPropertyName("deliveryEmployeeId")]
    public string? DeliveryEmployeeId { get; init; }
    [JsonPropertyName("deliveryEmployeeSubId")]
    public string? DeliveryEmployeeSubId { get; init; }
    [JsonPropertyName("vehicle")]
    public string? Vehicle { get; init; }
    [JsonPropertyName("soPhieu")]
    public string? SoPhieu { get; init; }
    [JsonPropertyName("soHoaDon")]
    public string? SoHoaDon { get; init; }
    [JsonPropertyName("ngayPhieu")]
    public string? NgayPhieu { get; init; }
    [JsonPropertyName("ngayHoaDon")]
    public string? NgayHoaDon { get; init; }
}

[JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Disallow)]
public sealed record ErpSalesOrderLineInput
{
    [JsonPropertyName("itemId")]
    public required string ItemId { get; init; }
    [JsonPropertyName("quantity")]
    public string? Quantity { get; init; }
    [JsonPropertyName("unitPrice")]
    public string? UnitPrice { get; init; }
    [JsonPropertyName("discountPercent")]
    public string? DiscountPercent { get; init; }
    [JsonPropertyName("vATPercent")]
    public string? VATPercent { get; init; }
    [JsonPropertyName("vATQuantity")]
    public string? VATQuantity { get; init; }
    [JsonPropertyName("dienGiai")]
    public string? DienGiai { get; init; }
    [JsonPropertyName("notes")]
    public string? Notes { get; init; }
    [JsonPropertyName("property")]
    public string? Property { get; init; }
    [JsonPropertyName("property2")]
    public string? Property2 { get; init; }
    [JsonPropertyName("parentId")]
    public string? ParentId { get; init; }
    [JsonPropertyName("notes2")]
    public string? Notes2 { get; init; }
    [JsonPropertyName("costId")]
    public string? CostId { get; init; }
    [JsonPropertyName("storeHouseId")]
    public string? StoreHouseId { get; init; }
    [JsonPropertyName("vATId")]
    public string? VATId { get; init; }
}

[JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Disallow)]
public sealed record ErpInternalTransferRequestHeaderInput
{
    [JsonPropertyName("documentDate")]
    public required string DocumentDate { get; init; }
    [JsonPropertyName("fromBranchId")]
    public required string FromBranchId { get; init; }
    [JsonPropertyName("toBranchId")]
    public required string ToBranchId { get; init; }
    [JsonPropertyName("requestedTransferDate")]
    public string? RequestedTransferDate { get; init; }
    [JsonPropertyName("transferReason")]
    public string? TransferReason { get; init; }
    [JsonPropertyName("transportMethod")]
    public string? TransportMethod { get; init; }
    [JsonPropertyName("notes")]
    public string? Notes { get; init; }
}

[JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Disallow)]
public sealed record ErpInternalTransferRequestLineInput
{
    [JsonPropertyName("itemId")]
    public required string ItemId { get; init; }
    [JsonPropertyName("requestedQty")]
    public required string RequestedQty { get; init; }
    [JsonPropertyName("requestedLot")]
    public string? RequestedLot { get; init; }
    [JsonPropertyName("expectedObjectId")]
    public string? ExpectedObjectId { get; init; }
    [JsonPropertyName("territoryNote")]
    public string? TerritoryNote { get; init; }
    [JsonPropertyName("isEquipment")]
    public required bool IsEquipment { get; init; }
    [JsonPropertyName("requestedAssetId")]
    public string? RequestedAssetId { get; init; }
    [JsonPropertyName("notes")]
    public string? Notes { get; init; }
}

[JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Disallow)]
public sealed record ErpMachineMovementHeaderInput
{
    [JsonPropertyName("documentDate")]
    public required string DocumentDate { get; init; }
    [JsonPropertyName("nguoiGiao")]
    public string? NguoiGiao { get; init; }
    [JsonPropertyName("nguoiNhan")]
    public string? NguoiNhan { get; init; }
    [JsonPropertyName("memo")]
    public string? Memo { get; init; }
    [JsonPropertyName("notes")]
    public string? Notes { get; init; }
    [JsonPropertyName("moveTypeId")]
    public required string MoveTypeId { get; init; }
    [JsonPropertyName("contractId")]
    public string? ContractId { get; init; }
    [JsonPropertyName("effectiveFrom")]
    public string? EffectiveFrom { get; init; }
    [JsonPropertyName("effectiveTo")]
    public string? EffectiveTo { get; init; }
    [JsonPropertyName("referenceNo")]
    public string? ReferenceNo { get; init; }
    [JsonPropertyName("referenceDate")]
    public string? ReferenceDate { get; init; }
    [JsonPropertyName("documentLink")]
    public string? DocumentLink { get; init; }
}

[JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Disallow)]
public sealed record ErpMachineMovementLineInput
{
    [JsonPropertyName("assetId")]
    public required string AssetId { get; init; }
    [JsonPropertyName("quantity")]
    public string? Quantity { get; init; }
    [JsonPropertyName("departmentId")]
    public string? DepartmentId { get; init; }
    [JsonPropertyName("objectId")]
    public string? ObjectId { get; init; }
    [JsonPropertyName("costCenterId")]
    public string? CostCenterId { get; init; }
    [JsonPropertyName("costId")]
    public string? CostId { get; init; }
    [JsonPropertyName("notes")]
    public string? Notes { get; init; }
    [JsonPropertyName("fromObjectId")]
    public string? FromObjectId { get; init; }
    [JsonPropertyName("fromStoreHouseId")]
    public string? FromStoreHouseId { get; init; }
    [JsonPropertyName("toStoreHouseId")]
    public string? ToStoreHouseId { get; init; }
    [JsonPropertyName("fromLocation")]
    public string? FromLocation { get; init; }
    [JsonPropertyName("toLocation")]
    public string? ToLocation { get; init; }
    [JsonPropertyName("handoverDate")]
    public string? HandoverDate { get; init; }
    [JsonPropertyName("handoverComponents")]
    public string? HandoverComponents { get; init; }
    [JsonPropertyName("assetCondition")]
    public string? AssetCondition { get; init; }
    [JsonPropertyName("toLocationId")]
    public string? ToLocationId { get; init; }
    [JsonPropertyName("toQuanHuyen")]
    public string? ToQuanHuyen { get; init; }
    [JsonPropertyName("toXaPhuong")]
    public string? ToXaPhuong { get; init; }
    [JsonPropertyName("toChuyenKhoa")]
    public string? ToChuyenKhoa { get; init; }
    [JsonPropertyName("toZoneId")]
    public string? ToZoneId { get; init; }
}

[JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Disallow)]
public sealed record ErpMachineRepairHeaderInput
{
    [JsonPropertyName("documentDate")]
    public required string DocumentDate { get; init; }
    [JsonPropertyName("nguoiGiao")]
    public string? NguoiGiao { get; init; }
    [JsonPropertyName("nguoiNhan")]
    public string? NguoiNhan { get; init; }
    [JsonPropertyName("memo")]
    public string? Memo { get; init; }
    [JsonPropertyName("notes")]
    public string? Notes { get; init; }
    [JsonPropertyName("serviceTypeId")]
    public required string ServiceTypeId { get; init; }
    [JsonPropertyName("objectId")]
    public string? ObjectId { get; init; }
    [JsonPropertyName("serviceLocation")]
    public string? ServiceLocation { get; init; }
    [JsonPropertyName("contractId")]
    public string? ContractId { get; init; }
    [JsonPropertyName("startDate")]
    public string? StartDate { get; init; }
    [JsonPropertyName("endDate")]
    public string? EndDate { get; init; }
    [JsonPropertyName("technician")]
    public string? Technician { get; init; }
    [JsonPropertyName("serviceStatus")]
    public string? ServiceStatus { get; init; }
    [JsonPropertyName("referenceNo")]
    public string? ReferenceNo { get; init; }
    [JsonPropertyName("referenceDate")]
    public string? ReferenceDate { get; init; }
    [JsonPropertyName("documentLink")]
    public string? DocumentLink { get; init; }
}

[JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Disallow)]
public sealed record ErpMachineRepairLineInput
{
    [JsonPropertyName("assetId")]
    public required string AssetId { get; init; }
    [JsonPropertyName("noiDung")]
    public string? NoiDung { get; init; }
    [JsonPropertyName("quantity")]
    public string? Quantity { get; init; }
    [JsonPropertyName("notes")]
    public string? Notes { get; init; }
    [JsonPropertyName("problemDescription")]
    public string? ProblemDescription { get; init; }
    [JsonPropertyName("actionTaken")]
    public string? ActionTaken { get; init; }
    [JsonPropertyName("resultStatus")]
    public string? ResultStatus { get; init; }
    [JsonPropertyName("warrantyCovered")]
    public bool? WarrantyCovered { get; init; }
    [JsonPropertyName("nextServiceDate")]
    public string? NextServiceDate { get; init; }
    [JsonPropertyName("laborAmount")]
    public string? LaborAmount { get; init; }
    [JsonPropertyName("internalAlert")]
    public string? InternalAlert { get; init; }
}
