import {z} from "zod";
import {sessionSchema,workspaceSchema,pageSchema,detailSchema,type DocumentKind} from "./contracts";
export class ApiError extends Error{constructor(public status:number,public code:string,public correlationId?:string){super(code);}}
export function errorMessage(e:unknown){if(!(e instanceof ApiError))return "Không thể kết nối. Vui lòng thử lại.";if((e.code==="backend_not_configured"||e.code==="frontend_not_configured"))return "Chưa có kết nối tới hệ thống ERP.";if(e.code==="backend_unavailable"||e.code==="identity_unavailable")return "Hệ thống ERP tạm thời không khả dụng. Vui lòng thử lại sau.";if(e.status===401)return "Vui lòng đăng nhập ERP để tiếp tục.";if(e.status===403)return "Bạn không có quyền truy cập dữ liệu này.";if(e.status===404)return "Chứng từ không còn khả dụng trong phạm vi của bạn.";if(e.status===429)return "Có quá nhiều yêu cầu. Vui lòng thử lại sau một phút.";return "Không thể hoàn tất yêu cầu. Vui lòng thử lại.";}
export async function request<S extends z.ZodTypeAny>(path:string,schema:S,init?:RequestInit):Promise<z.output<S>>{const r=await fetch(`/api/erp/${path}`,{...init,credentials:"same-origin",cache:"no-store",redirect:"error"});const body:unknown=await r.json().catch(()=>null);if(!r.ok){const p=z.object({code:z.string().optional()}).passthrough().safeParse(body);throw new ApiError(r.status,p.success?(p.data.code??"request_failed"):"request_failed",r.headers.get("x-correlation-id")??undefined);}const p=schema.safeParse(body);if(!p.success)throw new ApiError(502,"invalid_api_response");return p.data;}
export const getWorkspace=(signal?:AbortSignal)=>request("api/workspace",workspaceSchema,{signal});export const getSession=(signal?:AbortSignal)=>request("api/auth/session",sessionSchema,{signal});
const csrf=async()=>(await request("api/auth/csrf",z.object({token:z.string().min(1)}))).token;
export const login=async(username:string,password:string)=>request("api/auth/login",sessionSchema,{method:"POST",headers:{"Content-Type":"application/json","X-CSRF-TOKEN":await csrf()},body:JSON.stringify({username,password})});
export const continueSession=async()=>request("api/auth/session/continue",sessionSchema,{method:"POST",headers:{"X-CSRF-TOKEN":await csrf()}});
export async function logout(){const r=await fetch("/api/erp/api/auth/logout",{method:"POST",credentials:"same-origin",cache:"no-store",redirect:"error",headers:{"X-CSRF-TOKEN":await csrf()}});if(!r.ok&&r.status!==401)throw new ApiError(r.status,"logout_failed");}
export const getDocuments=(kind:DocumentKind,page:number,search:string,branchId:string,signal?:AbortSignal)=>request(`api/documents/${kind}?${new URLSearchParams({page:String(page),pageSize:"50",search,branchId})}`,pageSchema,{signal});
export async function getDetail(kind:DocumentKind,documentId:string,page:number,signal?:AbortSignal){const detail=await request(`api/documents/${kind}/detail?${new URLSearchParams({documentId,page:String(page),pageSize:"50"})}`,detailSchema,{signal});if(detail.document.documentId!==documentId||detail.page!==page)throw new ApiError(502,"invalid_api_response");return detail;}
export async function getHealth(signal?:AbortSignal){const r=await fetch("/api/erp/health/ready",{signal,cache:"no-store"});const d:unknown=await r.json();const p=z.object({checks:z.array(z.object({component:z.string(),status:z.string()})),status:z.string()}).safeParse(d);if(p.success)return p.data;const e=z.object({code:z.string()}).safeParse(d);throw new ApiError(r.status,e.success?e.data.code:"backend_unavailable");}
