import {z} from "zod";
const id=z.string().min(1).max(120);const label=z.string().min(1).max(250);const value=z.union([z.string().max(10000),z.boolean(),z.null()]);
const field=z.object({id,label,sectionId:id,kind:z.enum(["text","decimal","date","boolean","enum","lookup"]),required:z.boolean().optional(),readOnly:z.boolean().optional(),maxLength:z.number().int().min(1).max(10000).optional(),options:z.array(z.object({id,label}).strict()).max(200).optional(),lookupId:id.optional()}).strict();
export const screenDefinitionSchema=z.object({id,version:id,label,sections:z.array(z.object({id,label}).strict()).min(1).max(30),fields:z.array(field).max(300),actions:z.array(z.object({id,label,enabled:z.boolean(),reason:z.string().max(500).optional()}).strict()).max(30)}).strict().superRefine((definition,context)=>{
 const sections=new Set(definition.sections.map(s=>s.id));const fields=new Set(definition.fields.map(f=>f.id));const actions=new Set(definition.actions.map(a=>a.id));
 if(sections.size!==definition.sections.length||fields.size!==definition.fields.length||actions.size!==definition.actions.length)context.addIssue({code:"custom",message:"Duplicate stable ID"});
 for(const f of definition.fields){if(!sections.has(f.sectionId)||f.kind==="lookup"&&!f.lookupId||f.kind==="enum"&&!f.options?.length)context.addIssue({code:"custom",message:"Unresolved field descriptor"});}
});
export const documentSnapshotSchema=z.object({id,version:id,values:z.record(value),definition:screenDefinitionSchema}).strict().superRefine((snapshot,context)=>{const fields=new Set(snapshot.definition.fields.map(f=>f.id));if(Object.keys(snapshot.values).some(key=>!fields.has(key)))context.addIssue({code:"custom",message:"Unknown field value"});});
export const roleNavigationSchema=z.object({roleId:id,roleLabel:label,version:id,canPublish:z.boolean(),entries:z.array(z.object({screenId:id,label:z.string().min(1).max(24),enabled:z.boolean(),primary:z.boolean()}).strict()).max(4),allowedTargets:z.array(z.object({id,label}).strict()).max(256)}).strict().superRefine((config,context)=>{const targets=new Set(config.allowedTargets.map(t=>t.id));if(new Set(config.entries.map(e=>e.screenId)).size!==config.entries.length||config.entries.some(e=>!targets.has(e.screenId))||config.entries.filter(e=>e.primary&&e.enabled).length>1)context.addIssue({code:"custom",message:"Invalid authorized navigation configuration"});});
export const reportDefinitionSchema=z.object({id,version:id,label,description:z.string().max(1000),parameters:z.array(field).max(60),canRun:z.boolean()}).strict();
export const reportJobSchema=z.object({id,reportId:id,label,status:z.enum(["queued","running","completed","failed"]),createdAt:z.string().datetime(),snapshotAt:z.string().datetime().optional(),message:z.string().max(1000).optional(),referenceId:id.optional(),canDownload:z.boolean()}).strict();
