"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {useQuery} from "@tanstack/react-query";
import {Building2,ChevronLeft,ChevronRight,FileText,LockKeyhole,RefreshCw,Rows3,Search,ShieldCheck} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Badge} from "@/components/ui/badge";
import {Skeleton} from "@/components/ui/skeleton";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from "@/components/ui/empty";
import {ErpGrid} from "./grid";
import {ErrorPanel,Freshness} from "./feedback";
import {ApiError,getDocuments} from "@/lib/erp/api";
import {authorizedScreenIds} from "@/lib/erp/navigation";
import type {GridColumn} from "@/lib/erp/presentation";
import type {DocumentKind,DocumentRow,WorkspaceData} from "@/lib/erp/contracts";
const columns:GridColumn[]=[{id:"documentId",label:"Mã chứng từ",width:248,required:true},{id:"documentDate",label:"Ngày chứng từ",width:170,format:"date"},{id:"branchId",label:"Chi nhánh",width:160},{id:"statusId",label:"Mã trạng thái",width:160,format:"status"},{id:"isLocked",label:"Khóa chứng từ",width:170,format:"boolean"}];
const date=(value:string)=>new Intl.DateTimeFormat("vi-VN",{day:"2-digit",month:"2-digit",year:"numeric",timeZone:"UTC"}).format(new Date(value+"T00:00:00Z"));
function EmptyState({title,text,children}:{title:string;text:string;children?:React.ReactNode}){return <Empty className="erp-empty"><EmptyHeader><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{text}</EmptyDescription></EmptyHeader>{children}</Empty>;}
export function Documents({kind,workspace,compact,setCompact,onLogin,onDenied,renderDetail}:{kind:DocumentKind;workspace:WorkspaceData|null;compact:boolean;setCompact:(v:boolean)=>void;onLogin:()=>void;onDenied:(e:unknown)=>void;renderDetail:(selected:DocumentRow|null,close:()=>void)=>React.ReactNode}){
 const [search,setSearch]=useState("");const [applied,setApplied]=useState("");const [branch,setBranch]=useState("all");const [page,setPage]=useState(1);const [selected,setSelected]=useState<DocumentRow|null>(null);const searchRef=useRef<HTMLInputElement>(null);
 const allowed=authorizedScreenIds(workspace).includes(kind);const interval=kind==="inbound-requests"?15000:30000;
 const scopeKey=JSON.stringify([workspace?.session.tenantId,workspace?.session.companyId,workspace?.session.authorityVersion,workspace?.session.absoluteExpiresAt,kind,page,applied,branch]);
 const query=useQuery({queryKey:["erp-documents",scopeKey],queryFn:({signal})=>getDocuments(kind,page,applied,branch==="all"?"":branch,signal),enabled:allowed,gcTime:0,retry:false,staleTime:interval,refetchInterval:interval,refetchIntervalInBackground:false,refetchOnWindowFocus:true,refetchOnReconnect:false,networkMode:"always"});
 const denied=query.error instanceof ApiError&&[401,403].includes(query.error.status);const data=allowed&&!denied?query.data:undefined;
 // Reset selection before rendering a changed scope or denial; never show a stale document.
 const selectionScope=JSON.stringify([scopeKey,allowed,denied]);
 const [previousSelectionScope,setPreviousSelectionScope]=useState(selectionScope);
 if(previousSelectionScope!==selectionScope){setPreviousSelectionScope(selectionScope);setSelected(null);}
 useEffect(()=>{if(query.error)onDenied(query.error);},[query.error,onDenied]);
 useEffect(()=>{const listener=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="f"){e.preventDefault();searchRef.current?.focus();}};window.addEventListener("keydown",listener);return()=>window.removeEventListener("keydown",listener);},[]);
 const submit=(e:FormEvent)=>{e.preventDefault();setApplied(search.trim());setPage(1);if(applied===search.trim()&&page===1)void query.refetch();};
 const title=kind==="purchase-orders"?"Đặt mua hàng":"Đề nghị nhập hàng";
 function renderCell(row:DocumentRow,id:string){if(id==="documentId")return <button className="document-link" onClick={()=>setSelected(row)}><span className="document-cell-icon"><FileText size={15}/></span>{row.documentId}</button>;if(id==="documentDate")return date(row.documentDate);if(id==="branchId")return row.branchId;if(id==="statusId")return <Badge variant="outline">{row.statusId??"Chưa xác định"}</Badge>;return row.isLocked===null?"Chưa xác định":row.isLocked?<span className="locked"><LockKeyhole size={13}/>Đã khóa</span>:"Không khóa";}
 return <><section className="panel document-panel"><Tabs defaultValue="documents"><div className="document-tabs"><TabsList variant="line"><TabsTrigger value="documents">Danh sách chứng từ</TabsTrigger><TabsTrigger value="guide">Hướng dẫn</TabsTrigger></TabsList><span className="table-meta">{data?`${data.rows.length} chứng từ trên trang này`:"Dữ liệu từ ERP"}</span></div><TabsContent value="documents"><form className="table-toolbar" onSubmit={submit}><div className="search-field"><Search size={16}/><Input ref={searchRef} value={search} maxLength={50} onChange={e=>setSearch(e.target.value)} placeholder="Tìm mã chứng từ…" aria-label="Tìm mã chứng từ"/><kbd>⌘ F</kbd></div><Select value={branch} onValueChange={v=>{setBranch(v);setPage(1);}}><SelectTrigger className="branch-select" aria-label="Chi nhánh"><Building2 size={15}/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Tất cả chi nhánh được cấp quyền</SelectItem>{workspace?.branchIds.map(id=><SelectItem key={id} value={id}>{id}</SelectItem>)}</SelectContent></Select><Button type="submit" variant="secondary" disabled={!allowed}>Tìm kiếm</Button><div className="toolbar-end"><Button variant="outline" size="icon" aria-label={compact?"Giãn dòng":"Thu gọn dòng"} aria-pressed={compact} onClick={()=>setCompact(!compact)}><Rows3 size={16}/></Button><Button variant="outline" disabled={query.isFetching||!allowed} onClick={()=>void query.refetch()}><RefreshCw size={16} className={query.isFetching?"spin":""}/><span className="refresh-label">Làm mới</span></Button></div></form>
 {query.error&&<ErrorPanel error={query.error} retry={allowed?()=>void query.refetch():undefined}/>}
 {allowed&&!denied&&<div hidden={!data}><ErpGrid rows={data?.rows??[]} columns={columns} rowId={row=>row.documentId} renderCell={renderCell} mobileCard={row=><><div className="mobile-card-heading"><span className="document-cell-icon"><FileText size={17}/></span><strong>{row.documentId}</strong><ChevronRight size={18}/></div><div className="mobile-card-values"><div><span>Ngày chứng từ</span><strong>{date(row.documentDate)}</strong></div><div><span>Chi nhánh</span><strong>{row.branchId}</strong></div><div><span>Mã trạng thái</span><strong>{row.statusId??"Chưa xác định"}</strong></div><div><span>Khóa chứng từ</span><strong>{row.isLocked===null?"Chưa xác định":row.isLocked?"Đã khóa":"Không khóa"}</strong></div></div><span className="mobile-card-action">Xem chứng từ</span></>} onOpen={setSelected} schemaVersion="document-read-v1" scopeKey={scopeKey} compact={compact} label={title}/></div>}
 {!workspace?<EmptyState title="Chứng từ của bạn sẽ hiển thị tại đây" text="Đăng nhập ERP để xem chứng từ trong phạm vi được cấp quyền."><Button onClick={onLogin}><LockKeyhole size={16}/>Đăng nhập ERP</Button></EmptyState>:!allowed?<EmptyState title="Chưa được cấp quyền" text="Tài khoản ERP hiện tại không có quyền mở loại chứng từ này."/>:query.isPending&&!query.error?<div className="table-skeleton" role="status" aria-label="Đang tải chứng từ">{[1,2,3,4,5].map(i=><Skeleton key={i} className="h-10 w-full"/>)}</div>:data?.rows.length===0?<EmptyState title={applied||branch!=="all"?"Không có chứng từ phù hợp":"Chưa có chứng từ"} text={applied||branch!=="all"?"Thử điều chỉnh từ khóa hoặc chi nhánh.":"ERP chưa trả về chứng từ trong phạm vi của bạn."}/>:null}
 <div className="table-footer"><Freshness updatedAt={data?query.dataUpdatedAt:0} fetching={query.isFetching} stale={!!query.error}/><div className="pagination"><span>Trang {page}</span><Button variant="outline" size="icon" aria-label="Trang trước" disabled={page===1||query.isFetching||!allowed} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={16}/></Button><Button variant="outline" size="icon" aria-label="Trang tiếp theo" disabled={!data?.hasMore||query.isFetching||!allowed||page>=1000} onClick={()=>setPage(p=>p+1)}><ChevronRight size={16}/></Button></div></div></TabsContent><TabsContent value="guide"><div className="screen-guide"><h3>{title}</h3><p>Tìm kiếm và chọn chi nhánh gửi yêu cầu tới ERP. Bảng chỉ tải tối đa 50 chứng từ mỗi trang. Các dòng được chọn luôn thuộc trang đang mở.</p><div className="guide-grid"><div><ShieldCheck/><strong>Phạm vi được cấp quyền</strong><p>ERP xác nhận quyền và chi nhánh trước mỗi yêu cầu.</p></div><div><RefreshCw/><strong>Dữ liệu cập nhật</strong><p>Tự kiểm tra mỗi {interval/1000} giây khi màn hình đang mở và khi bạn quay lại.</p></div><div><Rows3/><strong>Bố cục cá nhân</strong><p>Ẩn, sắp xếp, cố định cột, đổi độ rộng và lưu chế độ xem trong phiên hiện tại.</p></div></div><p className="subtle-note">Trên điện thoại, bấm thẻ chứng từ để xem thông tin và dòng hàng. Thao tác tạo, sửa, duyệt và xuất dữ liệu sẽ xuất hiện theo quyền và dịch vụ nghiệp vụ được ERP cung cấp.</p></div></TabsContent></Tabs></section>{renderDetail(selected,()=>setSelected(null))}</>;
}
