"use client";
import {useEffect,useReducer,useRef,useState} from "react";
import {RefreshCw,Save,ShieldCheck} from "lucide-react";
import {toast} from "sonner";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Switch} from "@/components/ui/switch";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {RemoteLookup} from "./lookup";
import {useDirtyGuard} from "./navigation-guard";
import {editorReducer,type DocumentAdapter,type DocumentSnapshot,type LookupAdapter,type LookupValue,type OperationResult} from "@/lib/erp/presentation";
import {ApiError,errorMessage} from "@/lib/erp/api";

/** Mounted only with a validated server definition, snapshot and authorized adapter. */
export function DocumentEditor({snapshot,adapter,lookupAdapter,onConfirmed,onDenied}:{snapshot:DocumentSnapshot;adapter:DocumentAdapter;lookupAdapter:LookupAdapter;onConfirmed:(snapshot:DocumentSnapshot)=>void;onDenied:(error:unknown)=>void}){
 const [state,dispatch]=useReducer(editorReducer,{phase:"pristine",baseline:snapshot,values:{...snapshot.values}});const [section,setSection]=useState(snapshot.definition.sections[0]?.id??"");const [lookups,setLookups]=useState<Record<string,LookupValue|null>>({});const [clientErrors,setClientErrors]=useState<Record<string,string>>({});const [message,setMessage]=useState("");const lock=useRef(false);const alive=useRef(true);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const pending=["submitting","reconciling"].includes(state.phase);const uncertain=["unknown","reconciling"].includes(state.phase);useDirtyGuard(!["pristine","confirmed"].includes(state.phase),!pending&&!uncertain);
 const definition=state.baseline.definition;const fieldErrors=state.result?.kind==="rejected"?{...clientErrors,...state.result.fieldErrors}:clientErrors;
 function accept(result:OperationResult){dispatch({type:"result",result});if(result.kind==="confirmed"){onConfirmed(result.snapshot);toast.success("Đã lưu chứng từ.",{duration:3000});}else if(result.kind==="conflict")toast.warning("Chứng từ đã thay đổi. Hãy kiểm tra trước khi lưu lại.",{duration:6000});}
 async function submit(actionId:string){if(lock.current||uncertain||pending)return;const action=definition.actions.find(x=>x.id===actionId);if(!action?.enabled||!["dirty","rejected"].includes(state.phase))return;const errors:Record<string,string>={};for(const f of definition.fields){const value=state.values[f.id];if(f.required&&(value===null||value===undefined||value===""))errors[f.id]="Vui lòng nhập trường này.";if(f.kind==="decimal"&&typeof value==="string"&&value&&!/^-?\d{1,28}(?:\.\d{1,4})?$/.test(value))errors[f.id]="Nhập số thập phân, tối đa 4 chữ số sau dấu chấm.";}setClientErrors(errors);if(Object.keys(errors).length){const first=definition.fields.find(f=>errors[f.id]);if(first)setSection(first.sectionId);setMessage("Kiểm tra các trường được đánh dấu trước khi lưu.");return;}lock.current=true;setMessage("");dispatch({type:"submit"});try{const result=await adapter.save(state.baseline,{...state.values},actionId);if(alive.current)accept(result);}catch(e){if(alive.current)onDenied(e);if(alive.current)dispatch({type:"result",result:{kind:"unknown",message:"Chưa xác nhận được kết quả. Kiểm tra kết quả trước khi gửi lại.",referenceId:e instanceof ApiError?e.correlationId:undefined}});}finally{lock.current=false;}}
 async function reconcile(){if(lock.current||state.phase!=="unknown")return;lock.current=true;dispatch({type:"reconcile"});try{const result=await adapter.reconcile({documentId:state.baseline.id,version:state.baseline.version,referenceId:state.result?.referenceId});if(alive.current)accept(result);}catch(e){if(alive.current)onDenied(e);if(alive.current)dispatch({type:"result",result:{kind:"unknown",message:errorMessage(e),referenceId:state.result?.referenceId}});}finally{lock.current=false;}}
 async function reload(){if(lock.current)return;lock.current=true;try{const result=await adapter.reload(state.baseline.id);if(alive.current){dispatch({type:"reload",snapshot:result});setLookups({});setClientErrors({});setMessage("");}}catch(e){if(alive.current)onDenied(e);if(alive.current)setMessage(errorMessage(e));}finally{lock.current=false;}}
 const result=state.result;
 return <section className="panel document-editor" onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="s"){e.preventDefault();const action=definition.actions.find(a=>a.enabled);if(action)void submit(action.id);}}}><div className="panel-heading"><div><span className="page-eyebrow">{state.baseline.id}</span><h2>{definition.label}</h2></div><span className="editor-phase" role="status">{{pristine:"Chưa thay đổi",dirty:"Có thay đổi chưa lưu",submitting:"Đang gửi…",confirmed:"Đã lưu",rejected:"Cần điều chỉnh",conflict:"Xung đột phiên bản",unknown:"Chưa xác nhận kết quả",reconciling:"Đang kiểm tra kết quả…"}[state.phase]}</span></div>
 {message&&<div className="erp-feedback" role="alert">{message}</div>}{result&&result.kind!=="confirmed"&&<div className="erp-feedback operation-recovery" role="alert"><strong>{result.message}</strong>{result.referenceId&&<span>Mã hỗ trợ: <code>{result.referenceId}</code></span>}{state.phase==="unknown"&&<Button variant="outline" onClick={()=>void reconcile()}><RefreshCw size={15}/>Kiểm tra kết quả</Button>}{result.kind==="conflict"&&<><div className="conflict-comparison"><strong>Thay đổi cần kiểm tra</strong>{definition.fields.filter(f=>state.values[f.id]!==result.current.values[f.id]).map(f=><div key={f.id}><span>{f.label}</span><div><small>Bạn đang nhập</small><strong>{String(state.values[f.id]??"—")}</strong></div><div><small>Hiện tại trên ERP</small><strong>{String(result.current.values[f.id]??"—")}</strong></div></div>)}</div><div className="recovery-actions"><Button variant="outline" onClick={()=>void reload()}>Bỏ thay đổi và tải bản hiện tại</Button><Button onClick={()=>dispatch({type:"reapply"})}>Giữ nội dung để kiểm tra lại</Button></div></>}</div>}
 <Tabs value={section} onValueChange={setSection}><TabsList variant="line" className="document-section-tabs">{definition.sections.map(s=><TabsTrigger key={s.id} value={s.id}>{s.label}{definition.fields.some(f=>f.sectionId===s.id&&fieldErrors[f.id])&&<span className="tab-error" aria-label="Có lỗi">!</span>}</TabsTrigger>)}</TabsList>{definition.sections.map(s=><TabsContent key={s.id} value={s.id}><div className="document-field-grid">{definition.fields.filter(f=>f.sectionId===s.id).map(f=>{const id=`erp-field-${f.id}`;const error=fieldErrors[f.id];const disabled=f.readOnly||pending||uncertain||state.phase==="conflict";const value=state.values[f.id];return <div className="document-field" key={f.id}><label htmlFor={id}>{f.label}{f.required&&<span aria-label="Bắt buộc"> *</span>}</label>{f.kind==="boolean"?<Switch id={id} checked={value===true} disabled={disabled} aria-invalid={!!error} onCheckedChange={v=>dispatch({type:"change",id:f.id,value:v})}/>:f.kind==="enum"?<Select value={typeof value==="string"?value:undefined} disabled={disabled} onValueChange={v=>dispatch({type:"change",id:f.id,value:v})}><SelectTrigger id={id} aria-invalid={!!error} aria-describedby={error?`${id}-error`:undefined}><SelectValue placeholder={`Chọn ${f.label.toLowerCase()}`}/></SelectTrigger><SelectContent>{f.options?.map(option=><SelectItem key={option.id} value={option.id}>{option.label}</SelectItem>)}</SelectContent></Select>:f.kind==="lookup"&&f.lookupId?<RemoteLookup id={f.lookupId} label={f.label} value={lookups[f.id]??(typeof value==="string"&&value?{id:value,label:value}:null)} disabled={disabled} error={error} adapter={lookupAdapter} onChange={v=>{setLookups(old=>({...old,[f.id]:v}));dispatch({type:"change",id:f.id,value:v?.id??null});}}/>:<Input id={id} type={f.kind==="date"?"date":"text"} inputMode={f.kind==="decimal"?"decimal":undefined} value={typeof value==="string"?value:""} disabled={disabled} maxLength={f.maxLength??250} aria-invalid={!!error} aria-describedby={error?`${id}-error`:undefined} onChange={e=>dispatch({type:"change",id:f.id,value:e.target.value})}/>} {error&&<p id={`${id}-error`} className="field-error">{error}</p>}</div>;})}</div></TabsContent>)}</Tabs><div className="document-action-bar"><span><ShieldCheck size={14}/>ERP kiểm tra quyền, trạng thái và phiên bản khi lưu</span>{definition.actions.map(action=><Button key={action.id} disabled={!action.enabled||pending||uncertain||state.phase==="conflict"||!["dirty","rejected"].includes(state.phase)} title={action.reason} onClick={()=>void submit(action.id)}>{pending?<RefreshCw size={15} className="spin"/>:<Save size={15}/>} {action.label}</Button>)}</div></section>;
}
