"use client";
import {useEffect,useMemo,useRef,useState,type CSSProperties,type ReactNode,type KeyboardEvent} from "react";
import {useTable,tableFeatures,columnOrderingFeature,columnVisibilityFeature,columnSizingFeature,type ColumnDef,type RowData} from "@tanstack/react-table";
import {useVirtualizer} from "@tanstack/react-virtual";
import {ArrowUp,ArrowDown,Pin,SlidersHorizontal,Save,RotateCcw,X} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Checkbox} from "@/components/ui/checkbox";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from "@/components/ui/table";
import {defaultView,restoreView,moveColumn,scopedSelection,type GridColumn,type GridView} from "@/lib/erp/presentation";
const features=tableFeatures({columnOrderingFeature,columnVisibilityFeature,columnSizingFeature});
export type GridProps<T extends RowData>={rows:T[];columns:GridColumn[];rowId:(row:T)=>string;renderCell:(row:T,column:string)=>ReactNode;mobileCard:(row:T)=>ReactNode;onOpen:(row:T)=>void;schemaVersion:string;scopeKey:string;compact:boolean;label:string};

/** Mechanics only. No business actions, local filtering, or synthetic totals. */
export function ErpGrid<T extends RowData>({rows,columns,rowId,renderCell,mobileCard,onOpen,schemaVersion,scopeKey,compact,label}:GridProps<T>){
 const [view,setView]=useState(()=>defaultView(columns,schemaVersion));const [views,setViews]=useState<GridView[]>([]);const [viewName,setViewName]=useState("");const [settings,setSettings]=useState(false);const [selection,setSelection]=useState<string[]>([]);const [recovery,setRecovery]=useState<string[]>([]);const [active,setActive]=useState({row:0,col:0});const anchor=useRef(0);const viewport=useRef<HTMLDivElement>(null);const grid=useRef<HTMLTableElement>(null);
 useEffect(()=>{setSelection([]);setActive({row:0,col:0});},[scopeKey]);
 useEffect(()=>{setView(old=>{const restored=restoreView(old,columns,schemaVersion);setRecovery(restored.retired);return restored.view;});},[columns,schemaVersion]);
 const ids=rows.map(rowId);const selected=scopedSelection(selection,ids);
 const defs=useMemo<ColumnDef<typeof features,T>[]>(()=>columns.map(c=>({id:c.id,accessorFn:row=>row,header:c.label,size:c.width})),[columns]);
 const table=useTable({features,data:rows,columns:defs,getRowId:rowId,state:{columnOrder:view.order,columnVisibility:Object.fromEntries(columns.map(c=>[c.id,!view.hidden.includes(c.id)])),columnSizing:view.widths}});
 const ordered=table.getVisibleLeafColumns();const pinned=ordered.filter(c=>view.pinned.includes(c.id));const unpinned=ordered.filter(c=>!view.pinned.includes(c.id));const orderedColumns=[...pinned,...unpinned];
 const pinWidth=pinned.reduce((sum,c)=>sum+c.getSize(),44);
 const rowHeight=compact?44:60;const virtualRows=useVirtualizer({count:rows.length,getScrollElement:()=>viewport.current,estimateSize:()=>rowHeight,overscan:6});
 const virtualColumns=useVirtualizer({horizontal:true,scrollMargin:pinWidth,count:unpinned.length,getScrollElement:()=>viewport.current,estimateSize:i=>unpinned[i]?.getSize()??160,overscan:2});
 const wide=unpinned.length>12;const renderedColumns=wide?[...pinned,...virtualColumns.getVirtualItems().map(v=>unpinned[v.index])]:orderedColumns;
 const renderedRows=rows.length>30?virtualRows.getVirtualItems():rows.map((_,index)=>({index,start:index*rowHeight,end:(index+1)*rowHeight}));
 const totalWidth=orderedColumns.reduce((sum,c)=>sum+c.getSize(),44);const columnItems=virtualColumns.getVirtualItems();const padLeft=wide?(Math.max(0,(columnItems[0]?.start??pinWidth)-pinWidth)):0;const padRight=wide?Math.max(0,virtualColumns.getTotalSize()-((columnItems.at(-1)?.end??pinWidth)-pinWidth)):0;
 function toggle(index:number,range=false){const id=ids[index];if(!id)return;setSelection(old=>{const chosen=scopedSelection(old,ids);return range?[...new Set([...chosen,...ids.slice(Math.min(anchor.current,index),Math.max(anchor.current,index)+1)])]:chosen.includes(id)?chosen.filter(x=>x!==id):[...chosen,id];});if(!range)anchor.current=index;}
 function focusCell(row:number,col:number){const r=Math.max(0,Math.min(rows.length-1,row));const c=Math.max(0,Math.min(orderedColumns.length-1,col));setActive({row:r,col:c});virtualRows.scrollToIndex(r);const target=orderedColumns[c];const index=unpinned.findIndex(x=>x.id===target?.id);if(wide&&index>=0)virtualColumns.scrollToIndex(index);requestAnimationFrame(()=>requestAnimationFrame(()=>grid.current?.querySelector<HTMLElement>(`[data-cell="${r}:${c}"]`)?.focus()));}
 function keyboard(e:KeyboardEvent,r:number,c:number){if(e.target!==e.currentTarget)return;const movements:Record<string,[number,number]>={ArrowDown:[r+1,c],ArrowUp:[r-1,c],ArrowLeft:[r,c-1],ArrowRight:[r,c+1],Home:[e.ctrlKey?0:r,0],End:[e.ctrlKey?rows.length-1:r,orderedColumns.length-1],PageDown:[r+8,c],PageUp:[r-8,c]};if(movements[e.key]){e.preventDefault();focusCell(...movements[e.key]);}else if(e.key==="Enter"){e.preventDefault();onOpen(rows[r]);}else if(e.key===" "){e.preventDefault();toggle(r,e.shiftKey);}else if(e.key==="Escape"){setSelection([]);}}
 function style(id:string):CSSProperties{const column=orderedColumns.find(c=>c.id===id)!;const index=pinned.findIndex(c=>c.id===id);return {width:column.getSize(),minWidth:column.getSize(),maxWidth:column.getSize(),...(index>=0?{position:"sticky",left:44+pinned.slice(0,index).reduce((sum,c)=>sum+c.getSize(),0),zIndex:2}:{} )};}
 function saveView(){const name=viewName.trim();if(!name||views.length>=10)return;const next={...view,id:crypto.randomUUID(),name};setViews(old=>[...old,next]);setView(next);setViewName("");}
 return <div className="erp-grid"><div className="grid-view-bar"><div><strong>{view.name}</strong><span>{selected.length?`${selected.length} dòng được chọn trên trang này`:"Enter: chi tiết · Phím mũi tên: di chuyển · Space: chọn"}</span></div><Button variant="outline" size="sm" onClick={()=>setSettings(true)}><SlidersHorizontal size={15}/>Tùy chỉnh bảng</Button></div>
 {recovery.length>0&&<p className="grid-recovery" role="status">Đã bỏ {recovery.length} cột không còn trong cấu hình. Các cột hợp lệ vẫn được giữ.</p>}
 {selected.length>0&&<div className="grid-selection" role="status"><span>Đã chọn {selected.length}/{rows.length} dòng của trang đang mở</span><Button variant="ghost" size="sm" onClick={()=>setSelection([])}><X size={14}/>Bỏ chọn</Button></div>}
 <div className="desktop-grid-viewport" ref={viewport} style={{"--grid-row-height":`${rowHeight}px`,height:Math.min(480,44+rows.length*rowHeight)} as CSSProperties}>
 <Table ref={grid} role="grid" aria-label={label} aria-rowcount={rows.length+1} aria-colcount={orderedColumns.length+1} className="shared-grid-table" style={{width:totalWidth}}><TableHeader><TableRow role="row"><TableHead role="columnheader" className="grid-select-cell"><Checkbox aria-label="Chọn tất cả dòng trên trang này" checked={rows.length>0&&selected.length===rows.length?true:selected.length?"indeterminate":false} disabled={!rows.length} onCheckedChange={value=>setSelection(value===true?ids:[])}/></TableHead>{pinned.map(c=><TableHead role="columnheader" key={c.id} style={style(c.id)}>{columns.find(x=>x.id===c.id)?.label}</TableHead>)}{padLeft>0&&<TableHead aria-hidden style={{width:padLeft,padding:0}}/>}{renderedColumns.filter(c=>!view.pinned.includes(c.id)).map(c=><TableHead role="columnheader" key={c.id} style={style(c.id)}><span>{columns.find(x=>x.id===c.id)?.label}</span><div className="column-resizer" role="separator" aria-orientation="vertical" aria-label={`Độ rộng ${columns.find(x=>x.id===c.id)?.label}`} tabIndex={0} onKeyDown={e=>{if(["ArrowLeft","ArrowRight"].includes(e.key)){e.preventDefault();setView(old=>({...old,widths:{...old.widths,[c.id]:Math.max(96,Math.min(600,c.getSize()+(e.key==="ArrowRight"?16:-16)))}}));}}} onPointerDown={e=>{e.preventDefault();const start=e.clientX;const width=c.getSize();const el=e.currentTarget;el.setPointerCapture(e.pointerId);const move=(event:PointerEvent)=>setView(old=>({...old,widths:{...old.widths,[c.id]:Math.max(96,Math.min(600,width+event.clientX-start))}}));const end=()=>{el.removeEventListener("pointermove",move);el.removeEventListener("pointerup",end);el.removeEventListener("pointercancel",end);};el.addEventListener("pointermove",move);el.addEventListener("pointerup",end);el.addEventListener("pointercancel",end);}}/></TableHead>)}{padRight>0&&<TableHead aria-hidden style={{width:padRight,padding:0}}/>}</TableRow></TableHeader><TableBody>
 {renderedRows[0]?.start>0&&<TableRow aria-hidden><TableCell colSpan={renderedColumns.length+3} style={{height:renderedRows[0].start,padding:0}}/></TableRow>}
 {renderedRows.map(v=>{const row=rows[v.index];return <TableRow key={rowId(row)} role="row" aria-rowindex={v.index+2} aria-selected={selected.includes(rowId(row))} data-state={selected.includes(rowId(row))?"selected":undefined} onDoubleClick={()=>onOpen(row)}><TableCell role="gridcell" className="grid-select-cell"><Checkbox aria-label={`Chọn ${rowId(row)}`} checked={selected.includes(rowId(row))} onCheckedChange={()=>toggle(v.index)}/></TableCell>{pinned.map(c=>{const index=orderedColumns.indexOf(c);return <TableCell key={c.id} role="gridcell" aria-colindex={index+2} style={style(c.id)} data-cell={`${v.index}:${index}`} tabIndex={active.row===v.index&&active.col===index?0:-1} onFocus={()=>setActive({row:v.index,col:index})} onKeyDown={e=>keyboard(e,v.index,index)}>{renderCell(row,c.id)}</TableCell>;})}{padLeft>0&&<TableCell aria-hidden style={{width:padLeft,padding:0}}/>}{renderedColumns.filter(c=>!view.pinned.includes(c.id)).map(c=>{const index=orderedColumns.indexOf(c);return <TableCell key={c.id} role="gridcell" aria-colindex={index+2} style={style(c.id)} data-cell={`${v.index}:${index}`} tabIndex={active.row===v.index&&active.col===index?0:-1} onFocus={()=>setActive({row:v.index,col:index})} onKeyDown={e=>keyboard(e,v.index,index)}>{renderCell(row,c.id)}</TableCell>;})}{padRight>0&&<TableCell aria-hidden style={{width:padRight,padding:0}}/>}</TableRow>;})}
 {rows.length>30&&renderedRows.length>0&&<TableRow aria-hidden><TableCell colSpan={renderedColumns.length+3} style={{height:Math.max(0,virtualRows.getTotalSize()-(renderedRows.at(-1)?.end??0)),padding:0}}/></TableRow>}
 </TableBody></Table></div>
 <div className="mobile-document-list" aria-label={label}>{rows.map(row=><button type="button" className="mobile-document-card" key={rowId(row)} onClick={()=>onOpen(row)}>{mobileCard(row)}</button>)}</div>
 <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="grid-settings-modal"><DialogHeader><DialogTitle>Tùy chỉnh bảng</DialogTitle><DialogDescription>Cột và bố cục cá nhân. Các chế độ xem được giữ trong phiên đang mở; dữ liệu và quyền truy cập do ERP xác nhận.</DialogDescription></DialogHeader><div className="saved-view-list"><Button variant={view.id==="default"?"secondary":"outline"} size="sm" onClick={()=>setView(defaultView(columns,schemaVersion))}>Mặc định</Button>{views.map(v=><div key={v.id}><Button variant={view.id===v.id?"secondary":"outline"} size="sm" onClick={()=>{const restored=restoreView(v,columns,schemaVersion);setView(restored.view);setRecovery(restored.retired);}}>{v.name}</Button><Button variant="ghost" size="icon" aria-label={`Xóa chế độ xem ${v.name}`} onClick={()=>{setViews(old=>old.filter(x=>x.id!==v.id));if(view.id===v.id)setView(defaultView(columns,schemaVersion));}}><X size={13}/></Button></div>)}</div><div className="column-settings-list">{view.order.map((id,index)=>{const c=columns.find(x=>x.id===id);if(!c)return null;return <div className="column-setting" key={id}><Checkbox checked={!view.hidden.includes(id)} disabled={c.required} aria-label={`Hiển thị ${c.label}`} onCheckedChange={value=>setView(old=>({...old,hidden:value===true?old.hidden.filter(x=>x!==id):[...old.hidden,id]}))}/><span>{c.label}</span><Input type="number" min={96} max={600} aria-label={`Độ rộng ${c.label}`} value={view.widths[id]} onChange={e=>{const n=e.target.valueAsNumber;if(Number.isFinite(n))setView(old=>({...old,widths:{...old.widths,[id]:Math.max(96,Math.min(600,n))}}));}}/><Button variant={view.pinned.includes(id)?"secondary":"ghost"} size="icon" aria-label={`Cố định ${c.label}`} aria-pressed={view.pinned.includes(id)} onClick={()=>setView(old=>({...old,pinned:old.pinned.includes(id)?old.pinned.filter(x=>x!==id):[...old.pinned,id]}))}><Pin size={14}/></Button><Button variant="ghost" size="icon" disabled={index===0} aria-label={`Đưa ${c.label} lên`} onClick={()=>setView(old=>({...old,order:moveColumn(old.order,id,-1)}))}><ArrowUp size={14}/></Button><Button variant="ghost" size="icon" disabled={index===view.order.length-1} aria-label={`Đưa ${c.label} xuống`} onClick={()=>setView(old=>({...old,order:moveColumn(old.order,id,1)}))}><ArrowDown size={14}/></Button></div>;})}</div><form className="save-view-form" onSubmit={e=>{e.preventDefault();saveView();}}><Input aria-label="Tên chế độ xem" placeholder="Tên chế độ xem cá nhân" value={viewName} maxLength={60} onChange={e=>setViewName(e.target.value)}/><Button disabled={!viewName.trim()||views.length>=10}><Save size={14}/>Lưu bố cục</Button></form><Button variant="ghost" onClick={()=>setView(defaultView(columns,schemaVersion))}><RotateCcw size={14}/>Khôi phục bố cục mặc định</Button></DialogContent></Dialog>
 </div>;
}
