"use client";
import {useEffect,useState} from "react";
import {Search,X} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Command,CommandInput,CommandList,CommandEmpty,CommandItem} from "@/components/ui/command";
import {ErrorPanel} from "./feedback";
import type {LookupAdapter,LookupValue} from "@/lib/erp/presentation";
export function RemoteLookup({id,label,value,onChange,adapter,disabled,error}:{id:string;label:string;value:LookupValue|null;onChange:(value:LookupValue|null)=>void;adapter:LookupAdapter;disabled?:boolean;error?:string}){
 const [open,setOpen]=useState(false);const [query,setQuery]=useState("");const [items,setItems]=useState<LookupValue[]>([]);const [hasMore,setHasMore]=useState(false);const [busy,setBusy]=useState(false);const [failure,setFailure]=useState<unknown>(null);const [refresh,setRefresh]=useState(0);
 useEffect(()=>{if(!open)return;const controller=new AbortController();setItems([]);setBusy(true);setFailure(null);const timer=setTimeout(()=>{void adapter(id,query,controller.signal).then(result=>{if(controller.signal.aborted)return;setItems(result.items);setHasMore(result.hasMore);}).catch(e=>{if(!controller.signal.aborted)setFailure(e);}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});},250);return()=>{clearTimeout(timer);controller.abort();};},[open,id,query,adapter,refresh]);
 return <div className="remote-lookup"><Button type="button" variant="outline" className="lookup-trigger" disabled={disabled} aria-invalid={!!error||value?.unresolved} aria-label={label} aria-haspopup="dialog" onClick={()=>{setQuery("");setOpen(true);}}><span>{value?.label??`Chọn ${label.toLowerCase()}`}</span><Search size={15}/></Button>{value&&!disabled&&<Button type="button" variant="ghost" size="icon" aria-label={`Bỏ chọn ${label}`} onClick={()=>onChange(null)}><X size={15}/></Button>}{value?.unresolved&&<p className="field-error">Mã {value.id} không còn khả dụng. Giá trị lịch sử vẫn được giữ để kiểm tra.</p>}<Dialog open={open} onOpenChange={setOpen}><DialogContent className="lookup-modal"><DialogHeader><DialogTitle>Chọn {label.toLowerCase()}</DialogTitle><DialogDescription>Tìm trong phạm vi được ERP cấp quyền. Dùng phím mũi tên và Enter để chọn.</DialogDescription></DialogHeader><Command shouldFilter={false}><CommandInput value={query} onValueChange={setQuery} maxLength={100} placeholder={`Tìm ${label.toLowerCase()}…`}/><CommandList aria-busy={busy}>{busy?<p className="lookup-state" role="status">Đang tìm kiếm…</p>:failure?<ErrorPanel error={failure} retry={()=>setRefresh(v=>v+1)}/>:<><CommandEmpty>Không có kết quả phù hợp.</CommandEmpty>{items.map(item=><CommandItem key={item.id} value={item.id} onSelect={()=>{onChange(item);setOpen(false);}}><div><strong>{item.label}</strong><span className="lookup-context">{item.id}{item.context?` · ${item.context}`:""}</span></div></CommandItem>)}{hasMore&&<p className="lookup-state">Nhập từ khóa cụ thể hơn để thu hẹp kết quả.</p>}</>}</CommandList></Command></DialogContent></Dialog></div>;
}
