"use client";
import {useEffect,useRef,useState} from "react";
import {ArrowUp,ArrowDown,Menu,Plus,Save,X} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Switch} from "@/components/ui/switch";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {toast} from "sonner";
import {ErrorPanel} from "./feedback";
import {useDirtyGuard} from "./navigation-guard";
import type {RoleNavigation,RoleNavigationAdapter} from "@/lib/erp/presentation";
import {ApiError} from "@/lib/erp/api";
/** BE supplies the selected role, allowed stable targets, version and admin authorization. */
export function RoleNavigationEditor({configuration,adapter,onPublished,onDenied}:{configuration:RoleNavigation;adapter:RoleNavigationAdapter;onPublished:(next:RoleNavigation)=>void;onDenied:(error:unknown)=>void}){
 const [baseline,setBaseline]=useState(configuration);const [draft,setDraft]=useState(configuration);const [busy,setBusy]=useState(false);const [error,setError]=useState<unknown>(null);const [target,setTarget]=useState("");const [conflict,setConflict]=useState<RoleNavigation|null>(null);const [uncertain,setUncertain]=useState(false);const lock=useRef(false);const alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const dirty=JSON.stringify(draft.entries)!==JSON.stringify(baseline.entries);useDirtyGuard(dirty||busy||uncertain,!busy&&!uncertain);
 if(!configuration.canPublish)return null;
 const change=(index:number,patch:Partial<RoleNavigation["entries"][number]>)=>setDraft(old=>({...old,entries:old.entries.map((e,i)=>i===index?{...e,...patch}:patch.primary?{...e,primary:false}:e)}));
 const move=(index:number,delta:number)=>setDraft(old=>{const entries=[...old.entries];[entries[index],entries[index+delta]]=[entries[index+delta],entries[index]];return {...old,entries};});
 async function publish(){if(lock.current||!dirty||conflict||uncertain)return;lock.current=true;setBusy(true);setError(null);try{const saved=await adapter.publish(draft);if(!alive.current)return;setBaseline(saved);setDraft(saved);onPublished(saved);toast.success("Đã cập nhật điều hướng cho vai trò.");}catch(e){if(!alive.current)return;onDenied(e);setError(e);if(!(e instanceof ApiError&&[400,401,403,409,422].includes(e.status)))setUncertain(true);if(e instanceof ApiError&&e.status===409){try{setConflict(await adapter.reload());}catch(reloadError){onDenied(reloadError);setError(reloadError);}}}finally{lock.current=false;setBusy(false);}}
 async function checkLatest(){if(lock.current)return;lock.current=true;setBusy(true);try{const current=await adapter.reload();if(!alive.current)return;setConflict(current);setUncertain(false);}catch(e){if(!alive.current)return;onDenied(e);setError(e);}finally{lock.current=false;setBusy(false);}}
 return <section className="panel role-nav-editor"><div className="panel-heading"><div><h2>Điều hướng nhanh trên điện thoại</h2><p className="setting-scope">Vai trò: {baseline.roleLabel} · Phiên bản: {baseline.version}</p></div></div><p className="panel-intro">Chọn màn hình, thứ tự và một thao tác nổi bật. Mục Menu luôn mở toàn bộ màn hình được cấp quyền. Bố cục này không cấp thêm quyền nghiệp vụ.</p>{!!error&&<ErrorPanel error={error}/>} {uncertain&&<div className="erp-feedback" role="alert"><strong>Chưa xác nhận được kết quả lưu cấu hình.</strong><Button variant="outline" disabled={busy} onClick={()=>void checkLatest()}>Kiểm tra cấu hình hiện tại</Button></div>} {conflict&&<div className="erp-feedback" role="alert"><strong>Cấu hình đã thay đổi trên hệ thống.</strong><p>Thứ tự hiện tại: {conflict.entries.map(e=>e.label).join(" → ")}</p><div className="recovery-actions"><Button variant="outline" onClick={()=>{setBaseline(conflict);setDraft(conflict);setConflict(null);setError(null);}}>Tải bản hiện tại</Button><Button onClick={()=>{setBaseline(conflict);setDraft(old=>({...conflict,entries:old.entries.filter(e=>conflict.allowedTargets.some(t=>t.id===e.screenId))}));setConflict(null);setError(null);}}>Giữ bố cục để kiểm tra lại</Button></div></div>}
 <div className="role-nav-entries">{draft.entries.map((entry,index)=><div className="role-nav-entry" key={entry.screenId}><div><strong>{baseline.allowedTargets.find(t=>t.id===entry.screenId)?.label??entry.screenId}</strong><Input aria-label={`Nhãn ${entry.screenId}`} maxLength={24} value={entry.label} disabled={busy} onChange={e=>change(index,{label:e.target.value})}/></div><label><Switch aria-label={`Bật ${entry.label}`} checked={entry.enabled} disabled={busy} onCheckedChange={v=>change(index,{enabled:v})}/>Bật</label><Button variant={entry.primary?"secondary":"ghost"} disabled={busy||!entry.enabled} aria-pressed={entry.primary} onClick={()=>change(index,{primary:!entry.primary})}>Nổi bật</Button><Button variant="ghost" size="icon" disabled={busy||index===0} aria-label={`Đưa ${entry.label} lên`} onClick={()=>move(index,-1)}><ArrowUp size={15}/></Button><Button variant="ghost" size="icon" disabled={busy||index===draft.entries.length-1} aria-label={`Đưa ${entry.label} xuống`} onClick={()=>move(index,1)}><ArrowDown size={15}/></Button><Button variant="ghost" size="icon" disabled={busy} aria-label={`Xóa ${entry.label}`} onClick={()=>setDraft(old=>({...old,entries:old.entries.filter((_,i)=>i!==index)}))}><X size={15}/></Button></div>)}</div><div className="role-nav-add"><Select value={target} onValueChange={setTarget} disabled={busy}><SelectTrigger aria-label="Màn hình cần thêm"><SelectValue placeholder="Chọn màn hình được phép"/></SelectTrigger><SelectContent>{baseline.allowedTargets.filter(t=>!draft.entries.some(e=>e.screenId===t.id)).map(t=><SelectItem key={t.id} value={t.id}>{t.label}</SelectItem>)}</SelectContent></Select><Button variant="outline" disabled={busy||!target||draft.entries.length>=4} onClick={()=>{const selected=baseline.allowedTargets.find(t=>t.id===target);if(selected){setDraft(old=>({...old,entries:[...old.entries,{screenId:selected.id,label:selected.label,enabled:true,primary:false}]}));setTarget("");}}}><Plus size={15}/>Thêm</Button></div><div className="role-nav-preview" aria-label="Xem trước điều hướng mobile">{draft.entries.filter(e=>e.enabled).map(e=><div key={e.screenId} data-primary={e.primary}><span>{e.label||"Chưa đặt nhãn"}</span></div>)}<div><Menu size={20}/><span>Menu</span></div></div><div className="document-action-bar"><span>Xem trước · Chưa áp dụng cho người dùng</span><Button disabled={busy||uncertain||!dirty||!!conflict||draft.entries.some(e=>!e.label.trim())} onClick={()=>void publish()}><Save size={15}/>{busy?"Đang lưu…":"Áp dụng cho vai trò"}</Button></div></section>;
}
