using Medcom.Contracts;

namespace Medcom.Api;

internal static class DocumentFieldCatalog
{
    internal static DocumentFieldContract? Get(string kind) => kind switch
    {
        "purchase-orders" => new(2,"purchase-orders",
            new("AP_OrderTbl",[
                new("DocumentID","document.purchaseOrderHeader.documentId","varchar(30)",false,"string",null,"rows[].purchaseOrderHeader.documentId"),
                new("DocumentDate","document.purchaseOrderHeader.documentDate","datetime",false,"string","sql-datetime-without-timezone","rows[].purchaseOrderHeader.documentDate"),
                new("ObjectID","document.purchaseOrderHeader.objectId","varchar(100)",false,"string",null,"rows[].purchaseOrderHeader.objectId"),
                new("Memo","document.purchaseOrderHeader.memo","nvarchar(200)",true,"string",null,"rows[].purchaseOrderHeader.memo"),
                new("Notes","document.purchaseOrderHeader.notes","nvarchar(200)",true,"string",null,"rows[].purchaseOrderHeader.notes"),
                new("DeliverDate","document.purchaseOrderHeader.deliverDate","datetime",true,"string","sql-datetime-without-timezone","rows[].purchaseOrderHeader.deliverDate"),
                new("CurrencyID","document.purchaseOrderHeader.currencyId","varchar(3)",false,"string",null,"rows[].purchaseOrderHeader.currencyId"),
                new("RateExchange","document.purchaseOrderHeader.rateExchange","float",false,"number",null,"rows[].purchaseOrderHeader.rateExchange"),
                new("BaseTotal","document.purchaseOrderHeader.baseTotal","decimal(28, 0)",true,"string","decimal-string","rows[].purchaseOrderHeader.baseTotal"),
                new("SearchField","document.purchaseOrderHeader.searchField","nvarchar(2000)",true,"string",null,"rows[].purchaseOrderHeader.searchField"),
                new("isLock","document.purchaseOrderHeader.isLock","bit",false,"boolean",null,"rows[].purchaseOrderHeader.isLock"),
                new("UserCreate","document.purchaseOrderHeader.userCreate","varchar(50)",true,"string",null,"rows[].purchaseOrderHeader.userCreate"),
                new("UserUpdate","document.purchaseOrderHeader.userUpdate","varchar(50)",true,"string",null,"rows[].purchaseOrderHeader.userUpdate"),
                new("DateUpdate","document.purchaseOrderHeader.dateUpdate","datetime",true,"string","sql-datetime-without-timezone","rows[].purchaseOrderHeader.dateUpdate"),
                new("DateCreate","document.purchaseOrderHeader.dateCreate","datetime",true,"string","sql-datetime-without-timezone","rows[].purchaseOrderHeader.dateCreate"),
                new("LinkID","document.purchaseOrderHeader.linkId","varchar(50)",true,"string",null,"rows[].purchaseOrderHeader.linkId"),
                new("ContractID","document.purchaseOrderHeader.contractId","nvarchar(100)",true,"string",null,"rows[].purchaseOrderHeader.contractId"),
                new("StatusID","document.purchaseOrderHeader.statusId","int",true,"integer",null,"rows[].purchaseOrderHeader.statusId"),
                new("BranchID","document.purchaseOrderHeader.branchId","varchar(50)",false,"string",null,"rows[].purchaseOrderHeader.branchId")]),
            new("AP_OrderDetailTbl",[
                new("UserAutoID","purchaseOrderLines[].fields.userAutoId","varchar(40)",false,"string",null,null),
                new("DocumentID","purchaseOrderLines[].fields.documentId","varchar(30)",false,"string",null,null),
                new("ItemID","purchaseOrderLines[].fields.itemId","nvarchar(50)",false,"string",null,null),
                new("Quantity","purchaseOrderLines[].fields.quantity","decimal(28, 2)",true,"string","decimal-string",null),
                new("UnitPrice","purchaseOrderLines[].fields.unitPrice","decimal(28, 4)",true,"string","decimal-string",null),
                new("SourceAmount","purchaseOrderLines[].fields.sourceAmount","decimal(18, 2)",true,"string","decimal-string",null),
                new("Amount","purchaseOrderLines[].fields.amount","decimal(28, 0)",true,"string","decimal-string",null),
                new("Notes","purchaseOrderLines[].fields.notes","nvarchar(100)",true,"string",null,null),
                new("Quantity2","purchaseOrderLines[].fields.quantity2","decimal(28, 4)",true,"string","decimal-string",null),
                new("Property","purchaseOrderLines[].fields.property","nvarchar(50)",true,"string",null,null),
                new("Property2","purchaseOrderLines[].fields.property2","nvarchar(50)",true,"string",null,null),
                new("ParentID","purchaseOrderLines[].fields.parentId","varchar(50)",true,"string",null,null)])),
        "inbound-requests" => new(2,"inbound-requests",
            new("IV_InboundRequestTbl",[
                new("DocumentID","document.inboundRequestHeader.documentId","varchar(50)",false,"string",null,"rows[].inboundRequestHeader.documentId"),
                new("DocumentDate","document.inboundRequestHeader.documentDate","datetime",false,"string","sql-datetime-without-timezone","rows[].inboundRequestHeader.documentDate"),
                new("OrderNumber","document.inboundRequestHeader.orderNumber","nvarchar(50)",false,"string",null,"rows[].inboundRequestHeader.orderNumber"),
                new("BranchID","document.inboundRequestHeader.branchId","varchar(50)",true,"string",null,"rows[].inboundRequestHeader.branchId"),
                new("InvoiceNo","document.inboundRequestHeader.invoiceNo","nvarchar(50)",false,"string",null,"rows[].inboundRequestHeader.invoiceNo"),
                new("DeclarationNumber","document.inboundRequestHeader.declarationNumber","varchar(50)",true,"string",null,"rows[].inboundRequestHeader.declarationNumber"),
                new("DeparturePoint","document.inboundRequestHeader.departurePoint","nvarchar(100)",false,"string",null,"rows[].inboundRequestHeader.departurePoint"),
                new("DestinationPoint","document.inboundRequestHeader.destinationPoint","nvarchar(100)",false,"string",null,"rows[].inboundRequestHeader.destinationPoint"),
                new("IsRain","document.inboundRequestHeader.isRain","bit",true,"boolean",null,"rows[].inboundRequestHeader.isRain"),
                new("OrderTypeID","document.inboundRequestHeader.orderTypeId","nvarchar(50)",false,"string",null,"rows[].inboundRequestHeader.orderTypeId"),
                new("ObjectID","document.inboundRequestHeader.objectId","varchar(50)",true,"string",null,"rows[].inboundRequestHeader.objectId"),
                new("TotalPalletQuantityByDocument","document.inboundRequestHeader.totalPalletQuantityByDocument","decimal(18, 0)",true,"string","decimal-string","rows[].inboundRequestHeader.totalPalletQuantityByDocument"),
                new("TotalBarrelQuantityByDocument","document.inboundRequestHeader.totalBarrelQuantityByDocument","decimal(18, 0)",true,"string","decimal-string","rows[].inboundRequestHeader.totalBarrelQuantityByDocument"),
                new("TotalPalletQuantityByReal","document.inboundRequestHeader.totalPalletQuantityByReal","decimal(18, 0)",true,"string","decimal-string","rows[].inboundRequestHeader.totalPalletQuantityByReal"),
                new("TotalBarrelQuantityByReal","document.inboundRequestHeader.totalBarrelQuantityByReal","decimal(18, 0)",true,"string","decimal-string","rows[].inboundRequestHeader.totalBarrelQuantityByReal"),
                new("ExcessPackageQuantity","document.inboundRequestHeader.excessPackageQuantity","decimal(18, 0)",true,"string","decimal-string","rows[].inboundRequestHeader.excessPackageQuantity"),
                new("LackOfPackageQuantity","document.inboundRequestHeader.lackOfPackageQuantity","decimal(18, 0)",true,"string","decimal-string","rows[].inboundRequestHeader.lackOfPackageQuantity"),
                new("DamagedPackageQuantity","document.inboundRequestHeader.damagedPackageQuantity","decimal(18, 0)",true,"string","decimal-string","rows[].inboundRequestHeader.damagedPackageQuantity"),
                new("PackageTypeID","document.inboundRequestHeader.packageTypeId","nvarchar(50)",true,"string",null,"rows[].inboundRequestHeader.packageTypeId"),
                new("IsDamageOutsidePackage","document.inboundRequestHeader.isDamageOutsidePackage","bit",true,"boolean",null,"rows[].inboundRequestHeader.isDamageOutsidePackage"),
                new("DamageDescription","document.inboundRequestHeader.damageDescription","nvarchar(500)",true,"string",null,"rows[].inboundRequestHeader.damageDescription"),
                new("DamageInsideStatusID","document.inboundRequestHeader.damageInsideStatusId","nvarchar(50)",true,"string",null,"rows[].inboundRequestHeader.damageInsideStatusId"),
                new("LocationDamageDetectedID","document.inboundRequestHeader.locationDamageDetectedId","nvarchar(50)",true,"string",null,"rows[].inboundRequestHeader.locationDamageDetectedId"),
                new("LocationDamageDescription","document.inboundRequestHeader.locationDamageDescription","nvarchar(500)",true,"string",null,"rows[].inboundRequestHeader.locationDamageDescription"),
                new("ResultDesciption","document.inboundRequestHeader.resultDesciption","nvarchar(max)",true,"string",null,"rows[].inboundRequestHeader.resultDesciption"),
                new("TotalQuantityInboundResult","document.inboundRequestHeader.totalQuantityInboundResult","decimal(18, 0)",true,"string","decimal-string","rows[].inboundRequestHeader.totalQuantityInboundResult"),
                new("GoodAwaitingInboundResult","document.inboundRequestHeader.goodAwaitingInboundResult","decimal(18, 0)",true,"string","decimal-string","rows[].inboundRequestHeader.goodAwaitingInboundResult"),
                new("ResultNote","document.inboundRequestHeader.resultNote","nvarchar(500)",true,"string",null,"rows[].inboundRequestHeader.resultNote"),
                new("DatetimeRecorded","document.inboundRequestHeader.datetimeRecorded","datetime",true,"string","sql-datetime-without-timezone","rows[].inboundRequestHeader.datetimeRecorded"),
                new("StatusID","document.inboundRequestHeader.statusId","int",false,"integer",null,"rows[].inboundRequestHeader.statusId"),
                new("CurrencyID","document.inboundRequestHeader.currencyId","varchar(3)",true,"string",null,"rows[].inboundRequestHeader.currencyId"),
                new("RateExchange","document.inboundRequestHeader.rateExchange","decimal(28, 10)",true,"string","decimal-string","rows[].inboundRequestHeader.rateExchange"),
                new("ImageURL","document.inboundRequestHeader.imageUrl","varchar(255)",true,"string",null,"rows[].inboundRequestHeader.imageUrl"),
                new("BBKCUrl","document.inboundRequestHeader.bbkcUrl","varchar(255)",true,"string",null,"rows[].inboundRequestHeader.bbkcUrl"),
                new("Notes","document.inboundRequestHeader.notes","nvarchar(500)",true,"string",null,"rows[].inboundRequestHeader.notes"),
                new("SendTo","document.inboundRequestHeader.sendTo","nvarchar(max)",true,"string",null,"rows[].inboundRequestHeader.sendTo"),
                new("QRPrintType","document.inboundRequestHeader.qrPrintType","varchar(10)",false,"string",null,"rows[].inboundRequestHeader.qrPrintType"),
                new("LinkID","document.inboundRequestHeader.linkId","varchar(50)",true,"string",null,"rows[].inboundRequestHeader.linkId")]),
            new("IV_InboundRequestDetailsTbl",[
                new("UserAutoID","inboundRequestLines[].fields.userAutoId","varchar(50)",false,"string",null,null),
                new("DocumentID","inboundRequestLines[].fields.documentId","varchar(50)",false,"string",null,null),
                new("ContractID","inboundRequestLines[].fields.contractId","nvarchar(100)",true,"string",null,null),
                new("ItemID","inboundRequestLines[].fields.itemId","varchar(50)",false,"string",null,null),
                new("HangSX","inboundRequestLines[].fields.hangSX","nvarchar(100)",true,"string",null,null),
                new("UnitFactor","inboundRequestLines[].fields.unitFactor","float",true,"number",null,null),
                new("Unit2","inboundRequestLines[].fields.unit2","nvarchar(50)",true,"string",null,null),
                new("Additional","inboundRequestLines[].fields.additional","bit",true,"boolean",null,null),
                new("LotNumberByDocument","inboundRequestLines[].fields.lotNumberByDocument","nvarchar(50)",true,"string",null,null),
                new("SetQuantityByDocument","inboundRequestLines[].fields.setQuantityByDocument","decimal(18, 0)",true,"string","decimal-string",null),
                new("BarrelQuantityByDocument","inboundRequestLines[].fields.barrelQuantityByDocument","decimal(18, 0)",true,"string","decimal-string",null),
                new("ExpireDateByDocument","inboundRequestLines[].fields.expireDateByDocument","datetime",true,"string","sql-datetime-without-timezone",null),
                new("LotNumberByReal","inboundRequestLines[].fields.lotNumberByReal","nvarchar(50)",true,"string",null,null),
                new("SetQuantityByReal","inboundRequestLines[].fields.setQuantityByReal","decimal(18, 0)",true,"string","decimal-string",null),
                new("BarrelQuantityByReal","inboundRequestLines[].fields.barrelQuantityByReal","decimal(18, 0)",true,"string","decimal-string",null),
                new("ExpireDateByReal","inboundRequestLines[].fields.expireDateByReal","datetime",true,"string","sql-datetime-without-timezone",null),
                new("SourceAmount","inboundRequestLines[].fields.sourceAmount","decimal(18, 0)",true,"string","decimal-string",null),
                new("UnitPrice","inboundRequestLines[].fields.unitPrice","decimal(18, 0)",true,"string","decimal-string",null),
                new("Amount","inboundRequestLines[].fields.amount","decimal(18, 0)",true,"string","decimal-string",null),
                new("RandomTestQuantity","inboundRequestLines[].fields.randomTestQuantity","decimal(18, 0)",true,"string","decimal-string",null),
                new("TestStatus","inboundRequestLines[].fields.testStatus","nvarchar(100)",true,"string",null,null),
                new("NoPalletNote","inboundRequestLines[].fields.noPalletNote","nvarchar(500)",true,"string",null,null),
                new("PalletNote","inboundRequestLines[].fields.palletNote","nvarchar(500)",true,"string",null,null),
                new("CheckerNote","inboundRequestLines[].fields.checkerNote","nvarchar(500)",true,"string",null,null),
                new("ItemCode","inboundRequestLines[].fields.itemCode","nvarchar(50)",true,"string",null,null),
                new("ParentID","inboundRequestLines[].fields.parentId","varchar(50)",true,"string",null,null)])),
        "purchase-requests" => new(2,"purchase-requests",
            new("AP_PurchaseRequestTbl",[
                new("PurchaseRequestID","data.sourceFields.header.purchaseRequestId","nvarchar(50)",false,"string",null,"data.rows[].fields.purchaseRequestId"),
                new("PurchaseDate","data.sourceFields.header.purchaseDate","datetime",true,"string","sql-datetime-without-timezone","data.rows[].fields.purchaseDate"),
                new("PurposeID","data.sourceFields.header.purposeId","int",true,"integer",null,"data.rows[].fields.purposeId"),
                new("PersonSuggest","data.sourceFields.header.personSuggest","nvarchar(500)",false,"string",null,"data.rows[].fields.personSuggest"),
                new("Department","data.sourceFields.header.department","nvarchar(100)",false,"string",null,"data.rows[].fields.department"),
                new("PurposeDescOrClient","data.sourceFields.header.purposeDescOrClient","nvarchar(max)",true,"string",null,"data.rows[].fields.purposeDescOrClient"),
                new("Price","data.sourceFields.header.price","decimal(18, 2)",true,"string","decimal-string","data.rows[].fields.price"),
                new("Notes","data.sourceFields.header.notes","nvarchar(max)",true,"string",null,"data.rows[].fields.notes"),
                new("StatusID","data.sourceFields.header.statusId","int",false,"integer",null,"data.rows[].fields.statusId"),
                new("isLock","data.sourceFields.header.isLock","bit",true,"boolean",null,"data.rows[].fields.isLock"),
                new("CurrencyID","data.sourceFields.header.currencyId","varchar(3)",false,"string",null,"data.rows[].fields.currencyId"),
                new("ObjectID","data.sourceFields.header.objectId","varchar(100)",false,"string",null,"data.rows[].fields.objectId"),
                new("RateExchange","data.sourceFields.header.rateExchange","float",false,"number",null,"data.rows[].fields.rateExchange"),
                new("BranchID","data.sourceFields.header.branchId","varchar(50)",false,"string",null,"data.rows[].fields.branchId")]),
            new("AP_PurchaseRequestDetailTbl",[
                new("UserAutoID","data.sourceFields.lines[].userAutoId","varchar(50)",false,"string",null,null),
                new("ItemID","data.sourceFields.lines[].itemId","varchar(50)",false,"string",null,null),
                new("Budget","data.sourceFields.lines[].budget","decimal(18, 0)",true,"string","decimal-string",null),
                new("TimeRequired","data.sourceFields.lines[].timeRequired","nvarchar(200)",true,"string",null,null),
                new("Quantity","data.sourceFields.lines[].quantity","decimal(18, 0)",false,"string","decimal-string",null),
                new("UnitPrice","data.sourceFields.lines[].unitPrice","decimal(18, 0)",false,"string","decimal-string",null),
                new("TotalPrice","data.sourceFields.lines[].totalPrice","decimal(18, 0)",true,"string","decimal-string",null),
                new("Model","data.sourceFields.lines[].model","varchar(50)",true,"string",null,null),
                new("PurchaseRequestID","data.sourceFields.lines[].purchaseRequestId","nvarchar(50)",true,"string",null,null)])),
        _ => null
    };
}
