"""Generate fixed typed draft inputs from sanitized, finite current-form metadata."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'inventories/erp/20261010/six-screen-catalog.json'
OUTPUT = ROOT / 'src/backend/Medcom.Contracts/ErpDraftFields.cs'
NAMES = {
    'purchase-requests': 'PurchaseRequest', 'sales-orders': 'SalesOrder',
    'internal-transfer-requests': 'InternalTransferRequest',
    'machine-movements': 'MachineMovement', 'machine-repairs': 'MachineRepair',
}


def generate():
    catalog = json.loads(SOURCE.read_text(encoding='utf-8'))
    lines = ['// Generated by tools/source/generate_erp_screen_contracts.py from sanitized current-form metadata.',
             '// Fixed inputs only: document IDs, actors, branches, locks, workflow and calculated fields are server-owned.',
             'using System.Text.Json.Serialization;', 'namespace Medcom.Contracts;', '']
    for screen in catalog['screens']:
        if screen['id'] not in NAMES:
            continue
        for section, suffix in [('header', 'HeaderInput'), ('lines', 'LineInput')]:
            lines += ['[JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Disallow)]',
                      f"public sealed record Erp{NAMES[screen['id']]}{suffix}", '{']
            for field in screen['fields'][section]:
                if not field['writable']:
                    continue
                sql = field['type']
                value_type = {'bit': 'bool', 'int': 'int', 'smallint': 'short', 'tinyint': 'byte',
                              'bigint': 'long', 'float': 'double', 'real': 'float'}.get(sql, 'string')
                nullable = '?' if field['nullable'] else ''
                prop = field['name'][0].upper() + field['name'][1:]
                required = 'required ' if not field['nullable'] else ''
                lines += [f"    [JsonPropertyName(\"{field['name']}\")]",
                          f'    public {required}{value_type}{nullable} {prop} {{ get; init; }}']
            lines += ['}', '']
    return '\n'.join(lines)


if __name__ == '__main__':
    OUTPUT.write_text(generate(), encoding='utf-8', newline='\n')
    print('Fixed typed ERP draft inputs generated; no database connection or source SQL input.')
