import {test} from 'node:test';
import assert from 'node:assert/strict';
import {defaultView,restoreView,moveColumn,scopedSelection,sessionRemaining,editorReducer,validQuery} from '../.sites-runtime/erp-tests/presentation.js';
import {screenDefinitionSchema,documentSnapshotSchema,roleNavigationSchema} from '../.sites-runtime/erp-tests/ui-contracts.js';
const fields=[{id:'identity',label:'Identity',width:240,required:true},{id:'quantity',label:'Quantity',width:160}];
const definition={id:'verified-screen',version:'config-1',label:'Synthetic test',sections:[{id:'main',label:'Main'}],fields:[{id:'quantity',label:'Quantity',sectionId:'main',kind:'decimal'}],actions:[{id:'verified-save',label:'Save',enabled:true}]};
const snapshot={id:'synthetic-document',version:'opaque-1',values:{quantity:'1.0000'},definition};
const initial=()=>({phase:'pristine',baseline:snapshot,values:{...snapshot.values}});

test('schema drift retains valid presentation and rejects retired remapping',()=>{
 const saved={...defaultView(fields,'1'),order:['retired','quantity','identity'],hidden:['identity','retired'],widths:{identity:9999,quantity:NaN,retired:100},pinned:['retired','identity']};
 const {view,retired}=restoreView(saved,fields,'2');assert.deepEqual(view.order,['quantity','identity']);assert.deepEqual(view.hidden,[]);assert.deepEqual(view.pinned,['identity']);assert.equal(view.widths.identity,600);assert.equal(view.widths.quantity,160);assert.deepEqual(retired,['retired']);
});
test('100 potential columns restore without copying unknown IDs',()=>{
 const columns=Array.from({length:100},(_,i)=>({id:`field-${i}`,label:`Field ${i}`,width:160}));const view=defaultView(columns,'1');view.order.reverse();const restored=restoreView(view,columns.slice(0,99),'2');assert.equal(restored.view.order.length,99);assert.equal(new Set(restored.view.order).size,99);assert.deepEqual(restored.retired,['field-99']);
});
test('column moves preserve identity and stay within bounds',()=>{assert.deepEqual(moveColumn(['a','b','c'],'b',-1),['b','a','c']);assert.deepEqual(moveColumn(['a','b'],'a',-1),['a','b']);});
test('selection cannot widen from loaded page to the full query',()=>{assert.deepEqual(scopedSelection(['page-1','page-2','page-2','hidden'],['page-2','page-3']),['page-2']);});
test('session warning honors absolute expiry and invalid dates expire safely',()=>{const now=Date.parse('2026-10-04T00:00:00Z');assert.equal(sessionRemaining('2026-10-04T00:10:00Z','2026-10-04T00:02:00Z',now),120000);assert.equal(sessionRemaining('bad','bad',now),0);});
test('submit twice and edit during submit cannot change the first payload state',()=>{let state=editorReducer(initial(),{type:'change',id:'quantity',value:'2.1250'});state=editorReducer(state,{type:'submit'});assert.equal(state.phase,'submitting');assert.equal(editorReducer(state,{type:'submit'}),state);assert.equal(editorReducer(state,{type:'change',id:'quantity',value:'9'}),state);});
test('lost acknowledgement retains exact decimal input and prohibits blind replay',()=>{let state=editorReducer(initial(),{type:'change',id:'quantity',value:'999999999999999999.9999'});state=editorReducer(state,{type:'submit'});state=editorReducer(state,{type:'result',result:{kind:'unknown',message:'Lost acknowledgement'}});assert.equal(state.values.quantity,'999999999999999999.9999');assert.equal(editorReducer(state,{type:'submit'}),state);state=editorReducer(state,{type:'reconcile'});assert.equal(state.phase,'reconciling');});
test('conflict reapply preserves input, uses new opaque version, and respects schema/read-only changes',()=>{const current={...snapshot,version:'opaque-2',values:{quantity:'3.0000',protected:'server'},definition:{...definition,fields:[...definition.fields,{id:'protected',label:'Protected',sectionId:'main',kind:'text',readOnly:true}]}};let state={...initial(),values:{quantity:'2.0000',retired:'old',protected:'client'}};state=editorReducer(state,{type:'result',result:{kind:'conflict',message:'Changed',current}});assert.equal(state.values.quantity,'2.0000');state=editorReducer(state,{type:'reapply'});assert.equal(state.baseline.version,'opaque-2');assert.deepEqual(state.values,{quantity:'2.0000',protected:'server'});});
test('only authoritative confirmation resets dirty state',()=>{let state=editorReducer(initial(),{type:'change',id:'quantity',value:'2'});state=editorReducer(state,{type:'result',result:{kind:'rejected',message:'Invalid',fieldErrors:{quantity:'Invalid'}}});assert.equal(state.phase,'rejected');assert.equal(state.values.quantity,'2');state=editorReducer(state,{type:'result',result:{kind:'confirmed',snapshot:{...snapshot,version:'opaque-3',values:{quantity:'2.0000'}}}});assert.equal(state.phase,'confirmed');assert.equal(state.baseline.version,'opaque-3');assert.equal(state.values.quantity,'2.0000');});
test('editor rejects unknown or read-only field changes',()=>{const state=initial();assert.equal(editorReducer(state,{type:'change',id:'unknown',value:'x'}),state);const readOnly={...state,baseline:{...snapshot,definition:{...definition,fields:[{...definition.fields[0],readOnly:true}]}}};assert.equal(editorReducer(readOnly,{type:'change',id:'quantity',value:'9'}),readOnly);});
test('normalized definitions reject executable metadata, unknown fields and duplicate IDs',()=>{assert.equal(screenDefinitionSchema.safeParse({...definition,sql:'SELECT *'}).success,false);assert.equal(documentSnapshotSchema.safeParse({...snapshot,values:{...snapshot.values,unknown:'x'}}).success,false);assert.equal(screenDefinitionSchema.safeParse({...definition,fields:[...definition.fields,...definition.fields]}).success,false);});
test('role configuration validates authorized targets and one primary shortcut',()=>{const config={roleId:'role',roleLabel:'Role',version:'v1',canPublish:true,entries:[{screenId:'screen',label:'Screen',enabled:true,primary:true}],allowedTargets:[{id:'screen',label:'Screen'}]};assert.equal(roleNavigationSchema.safeParse(config).success,true);assert.equal(roleNavigationSchema.safeParse({...config,entries:[{...config.entries[0],screenId:'outside-scope'}]}).success,false);assert.equal(roleNavigationSchema.safeParse({...config,entries:[...config.entries,...config.entries]}).success,false);});
test('typed filters reject unknown fields/operators/options and keep decimal strings',()=>{const fields=[{id:'quantity',label:'Quantity',kind:'decimal',operators:['gte']}];const query={filters:[{fieldId:'quantity',operator:'gte',value:'12345678901234567890.1234'}],sort:[{fieldId:'identity',direction:'asc'}]};assert.equal(validQuery(query,fields,['identity'],[]),true);assert.equal(validQuery({...query,filters:[{...query.filters[0],fieldId:'dbo.secret'}]},fields,['identity'],[]),false);assert.equal(validQuery({...query,filters:[{...query.filters[0],operator:'like'}]},fields,['identity'],[]),false);assert.equal(validQuery({...query,groupId:'unknown'},fields,['identity'],[]),false);});
