// Synthetic native-browser acceptance for shared retained surface and footer.
import {test} from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {createServer} from 'node:http';import {once} from 'node:events';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {existsSync} from 'node:fs';import path from 'node:path';
const require=createRequire(import.meta.url),{build}=require('esbuild');
const output='.test-runtime/i50-record-browser';await mkdir(output,{recursive:true});
const entry=`import React,{useState} from 'react';import {createRoot} from 'react-dom/client';import {RecordDialog,RecordActionBar} from './components/erp/record-dialog';import {RequestButton} from './components/erp/request-presentation';import {NavigationGuardProvider,useNavigationGuard,useDirtyGuard} from './components/erp/navigation-guard';import {RecordDeleteConfirmation} from './components/erp/record-delete-confirmation';
window.i50={submits:0,deletes:0};function App(){const[allowed,setAllowed]=useState(true);window.i50.authority=setAllowed;return <NavigationGuardProvider authority={{lifecycleKey:'synthetic',presentationAllowed:allowed}}><Editor allowed={allowed}/></NavigationGuardProvider>;}
function Editor({allowed}){const[open,setOpen]=useState(true),[text,setText]=useState(''),[deleting,setDeleting]=useState(false);const guard=useNavigationGuard();useDirtyGuard(text!=='',false);window.i50.reopen=()=>setOpen(true);return <><button onClick={()=>setOpen(true)}>Open synthetic</button><RecordDialog open={open} presentationAllowed={allowed} title='Synthetic record' documentNumber='QA-001' closeLabel='Đóng' onRequestClose={()=>guard.request(()=>setOpen(false))}><form id='synthetic-form' onSubmit={e=>{e.preventDefault();window.i50.submits++;}}><label>Ghi chú tổng hợp<input aria-label='Ghi chú tổng hợp' value={text} onChange={e=>setText(e.target.value)}/></label><div style={{height:1400}}>Synthetic form geometry</div><RecordActionBar className='request-action-bar'><RequestButton type='submit' form='synthetic-form'>Synthetic review</RequestButton><RequestButton type='button' onClick={()=>setDeleting(true)}>Synthetic delete</RequestButton></RecordActionBar></form></RecordDialog><RecordDeleteConfirmation open={deleting} identity='Dòng 1 · QA-ITEM' presentationAllowed={allowed} isAllowed={()=>allowed} onCancel={()=>setDeleting(false)} onConfirm={()=>{window.i50.deletes++;setDeleting(false);}}/></>;}
createRoot(document.getElementById('root')).render(<App/>);`;
const fixture=await build({stdin:{contents:entry,resolveDir:process.cwd(),loader:'tsx'},bundle:true,write:false,outfile:output+'/fixture.js',platform:'browser',format:'iife',alias:{'@':process.cwd()},jsx:'automatic',define:{'process.env.NODE_ENV':'"production"','process.env':'{}'},logLevel:'warning'});
const script=fixture.outputFiles.find(file=>file.path.endsWith('.js')).contents;
const css=(await require('postcss')([require('@tailwindcss/postcss')({base:process.cwd()})]).process(await readFile('app/globals.css','utf8'),{from:path.resolve('app/globals.css')})).css+'\n'+fixture.outputFiles.filter(file=>file.path.endsWith('.css')).map(file=>file.text).join('\n');
await writeFile(output+'/compiled-fixture.js',script);
test('native record desktop/mobile footer, authority masking, nested modal and dirty close',async()=>{
 const executable=process.env.MEDCOM_EDGE_PATH??'/usr/bin/chromium';assert.ok(existsSync(executable),'Native Chromium/Edge required; compilation is not browser acceptance');
 const browserTools=process.env.MEDCOM_BROWSER_TOOL_HOME;const {chromium}=(browserTools?createRequire(path.join(browserTools,'package.json')):require)('playwright-core');
 const server=createServer((req,res)=>{if(req.url==='/fixture.js'){res.setHeader('content-type','text/javascript');res.end(script);}else{res.setHeader('content-type','text/html');res.end('<!doctype html><html lang="vi"><meta name="viewport" content="width=device-width,initial-scale=1"><style>'+css+'</style><body><div id="root"></div><script src="/fixture.js"></script></body></html>');}});server.listen(0,'127.0.0.1');await once(server,'listening');let browser;const results=[],errors=[];
 try{
  browser=await chromium.launch({executablePath:executable,headless:true,chromiumSandbox:true});
  for(const width of [390,1280]){const page=await browser.newPage({viewport:{width,height:850}});page.on('pageerror',error=>errors.push(String(error)));await page.goto('http://127.0.0.1:'+server.address().port);const dialog=page.getByRole('dialog',{name:'Synthetic record QA-001',exact:true});await dialog.waitFor();
   const action=dialog.getByRole('button',{name:'Synthetic review',exact:true});assert.equal(await action.evaluate(el=>el.closest('.record-dialog-actions')!==null),true);await action.click();assert.equal(await page.evaluate(()=>window.i50.submits),1,'portal preserves original form owner');
   const geometry=await action.evaluate(el=>{const r=el.getBoundingClientRect();return {top:r.top,bottom:r.bottom,height:r.height,viewport:innerHeight};});assert.ok(geometry.height>=44&&geometry.bottom<=geometry.viewport);await dialog.locator('.request-detail-body').evaluate(el=>el.scrollTop=el.scrollHeight);assert.equal(await action.isVisible(),true);
   const input=dialog.getByLabel('Ghi chú tổng hợp');await input.fill('RETAINED SYNTHETIC EDIT');const handle=await input.elementHandle();await page.evaluate(()=>window.i50.authority(false));assert.equal(await dialog.isVisible(),false);assert.equal(await handle.evaluate(el=>el.isConnected),true);await page.evaluate(()=>window.i50.authority(true));await dialog.waitFor();assert.equal(await input.inputValue(),'RETAINED SYNTHETIC EDIT');
   await dialog.getByRole('button',{name:'Synthetic delete',exact:true}).click();const nested=page.getByRole('alertdialog');await nested.waitFor();await nested.getByRole('button',{name:'Giữ dòng',exact:true}).click();assert.equal(await page.evaluate(()=>window.i50.deletes),0);assert.equal(await input.inputValue(),'RETAINED SYNTHETIC EDIT');
   await dialog.getByRole('button',{name:'Đóng',exact:true}).click();await nested.waitFor();await nested.getByRole('button',{name:'Tiếp tục làm việc',exact:true}).click();assert.equal(await input.inputValue(),'RETAINED SYNTHETIC EDIT');assert.equal(await dialog.isVisible(),true);await page.screenshot({path:output+'/record-'+width+'.png'});results.push({width,status:'PASS',footer:geometry});await page.close();
  }
  assert.deepEqual(errors,[]);await writeFile(output+'/evidence.json',JSON.stringify({status:'PASS',results,errors,browser:browser.version(),scope:'synthetic UI only'},null,2)+'\n');
 }finally{await browser?.close();await new Promise(resolve=>server.close(resolve));}
});
