// Synthetic native-browser acceptance for shared retained surface and footer.
import {test} from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {createServer} from 'node:http';import {once} from 'node:events';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {existsSync} from 'node:fs';import path from 'node:path';
const require=createRequire(import.meta.url),{build}=require('esbuild');
const output='.test-runtime/i50-record-browser';await mkdir(output,{recursive:true});
const entry=`import React,{useState} from 'react';import {createRoot} from 'react-dom/client';import {RecordDialog,RecordActionBar,RecordDetailToolbar} from './components/erp/record-dialog';import {RequestButton} from './components/erp/request-presentation';import {NavigationGuardProvider,useNavigationGuard,useDirtyGuard} from './components/erp/navigation-guard';import {RecordDeleteConfirmation} from './components/erp/record-delete-confirmation';
window.i50={submits:0,deletes:0,verifies:0};function App(){const[allowed,setAllowed]=useState(true);window.i50.authority=setAllowed;return <NavigationGuardProvider authority={{lifecycleKey:'synthetic',presentationAllowed:allowed}}><Editor allowed={allowed}/></NavigationGuardProvider>;}
function Editor({allowed}){const[open,setOpen]=useState(true),[text,setText]=useState(''),[deleting,setDeleting]=useState(false),[short,setShort]=useState(false);window.i50.short=setShort;const guard=useNavigationGuard();useDirtyGuard(text!=='',false);window.i50.reopen=()=>setOpen(true);return <><button onClick={()=>setOpen(true)}>Open synthetic</button><RecordDialog open={open} presentationAllowed={allowed} title='Synthetic record' documentNumber='QA-001' closeLabel='Đóng' onRequestClose={()=>guard.request(()=>setOpen(false))}><RecordDetailToolbar><RequestButton type='button' onClick={()=>guard.request(()=>setOpen(false))}>Đóng phiếu tổng hợp</RequestButton><RequestButton type='button' onClick={()=>window.i50.verifies++}>Xác minh lại quyền nhập hàng</RequestButton></RecordDetailToolbar><form id='synthetic-form' onSubmit={e=>{e.preventDefault();window.i50.submits++;}}><label>Ghi chú tổng hợp<input aria-label='Ghi chú tổng hợp' value={text} onChange={e=>setText(e.target.value)}/></label><div style={{height:short?40:1400}}>Synthetic form geometry</div><RecordActionBar className='request-action-bar'><RequestButton type='submit' form='synthetic-form'>Synthetic review</RequestButton><RequestButton type='button' onClick={()=>setDeleting(true)}>Synthetic delete</RequestButton></RecordActionBar></form></RecordDialog><RecordDeleteConfirmation open={deleting} identity='Dòng 1 · QA-ITEM' presentationAllowed={allowed} isAllowed={()=>allowed} onCancel={()=>setDeleting(false)} onConfirm={()=>{window.i50.deletes++;setDeleting(false);}}/></>;}
createRoot(document.getElementById('root')).render(<App/>);`;
const fixture=await build({stdin:{contents:entry,resolveDir:process.cwd(),loader:'tsx'},bundle:true,write:false,outfile:output+'/fixture.js',platform:'browser',format:'iife',alias:{'@':process.cwd()},jsx:'automatic',define:{'process.env.NODE_ENV':'"production"','process.env':'{}'},logLevel:'warning'});
const script=fixture.outputFiles.find(file=>file.path.endsWith('.js')).contents;
const css=(await require('postcss')([require('@tailwindcss/postcss')({base:process.cwd()})]).process(await readFile('app/globals.css','utf8'),{from:path.resolve('app/globals.css')})).css+'\n'+fixture.outputFiles.filter(file=>file.path.endsWith('.css')).map(file=>file.text).join('\n');
await writeFile(output+'/compiled-fixture.js',script);
test('native record desktop/mobile footer, authority masking, nested modal and dirty close',async()=>{
 const executable=process.env.MEDCOM_EDGE_PATH??'/usr/bin/chromium';assert.ok(existsSync(executable),'Native Chromium/Edge required; compilation is not browser acceptance');
 const browserTools=process.env.MEDCOM_BROWSER_TOOLCHAIN;const {chromium}=(browserTools?createRequire(path.join(path.resolve(browserTools),'package.json')):require)('playwright-core');
 const server=createServer((req,res)=>{if(req.url==='/fixture.js'){res.setHeader('content-type','text/javascript');res.end(script);}else{res.setHeader('content-type','text/html');res.end('<!doctype html><html lang="vi"><meta name="viewport" content="width=device-width,initial-scale=1"><style>'+css+'</style><body><div id="root"></div><script src="/fixture.js"></script></body></html>');}});server.listen(0,'127.0.0.1');await once(server,'listening');let browser;const results=[],errors=[];
 try{
  browser=await chromium.launch({executablePath:executable,headless:true,chromiumSandbox:true});
  for(const width of [390,1280]){const page=await browser.newPage({viewport:{width,height:850}});page.on('pageerror',error=>errors.push(String(error)));await page.goto('http://127.0.0.1:'+server.address().port);const dialog=page.getByRole('dialog',{name:'Synthetic record QA-001',exact:true});await dialog.waitFor();
   const assertFullscreen=async()=>{const box=await dialog.boundingBox(),viewport=page.viewportSize();assert.ok(box&&Math.abs(box.x)<=1&&Math.abs(box.y)<=1&&Math.abs(box.width-viewport.width)<=1&&Math.abs(box.height-viewport.height)<=1,'Short and long mobile dialogs must cover the full viewport: '+JSON.stringify({box,viewport}));};
   const assertLongLayout=async()=>{
    await page.waitForFunction(()=>!!document.querySelector('.record-dialog-actions .request-action-bar'));
    const body=dialog.locator('.request-detail-body');await body.evaluate(el=>el.scrollTop=0);
    const before=await dialog.evaluate(el=>{const rect=node=>{const r=node.getBoundingClientRect();return {top:r.top,bottom:r.bottom};};return {header:rect(el.querySelector('.request-detail-header')),footer:rect(el.querySelector('.record-dialog-actions'))};});
    const scroll=await body.evaluate(el=>{const initial=el.scrollTop;el.scrollTop=el.scrollHeight;return {initial,top:el.scrollTop,height:el.clientHeight,content:el.scrollHeight};});
    assert.ok(scroll.height>0&&scroll.content>scroll.height&&scroll.top>scroll.initial,'Long detail has a real bounded scroll owner: '+JSON.stringify(scroll));
    const after=await dialog.evaluate(el=>{const rect=node=>{const r=node.getBoundingClientRect();return {top:r.top,bottom:r.bottom};};return {header:rect(el.querySelector('.request-detail-header')),footer:rect(el.querySelector('.record-dialog-actions')),viewport:innerHeight};});
    for(const part of ['header','footer'])assert.ok(after[part].top>=0&&after[part].bottom<=after.viewport&&Math.abs(after[part].top-before[part].top)<=1&&Math.abs(after[part].bottom-before[part].bottom)<=1,'Header and footer remain visible and stationary while only the body scrolls: '+JSON.stringify({part,before,after}));
    await body.evaluate(el=>el.scrollTop=0);return scroll;
   };
   if(width<768)await assertFullscreen();await assertLongLayout();
   const toolbar=dialog.getByRole('group',{name:'Thao tác phiếu',exact:true});
   const assertToolbar=async()=>{const geometry=await toolbar.evaluate(el=>({gap:parseFloat(getComputedStyle(el).gap),width:innerWidth,buttons:[...el.querySelectorAll('button')].map(button=>{const r=button.getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,bottom:r.bottom,height:r.height};})}));assert.equal(geometry.gap,8);assert.ok(geometry.buttons.every(r=>r.left>=0&&r.right<=geometry.width&&r.height>=44),'Every recovery action fits at touch-target size');const [a,b]=geometry.buttons;assert.ok(b.left>=a.right+7||b.top>=a.bottom+7,'Close and Verify never touch or overlap');return geometry;};
   await assertToolbar();await toolbar.getByRole('button',{name:'Xác minh lại quyền nhập hàng',exact:true}).click();assert.equal(await page.evaluate(()=>window.i50.verifies),1,'Toolbar wrapping preserves the original verification callback');
   if(width===390){await page.setViewportSize({width:320,height:850});await assertFullscreen();await assertLongLayout();await assertToolbar();await page.screenshot({path:output+'/record-actions-320.png'});await page.setViewportSize({width,height:850});}
   await page.evaluate(()=>window.i50.short(true));await page.waitForFunction(()=>document.querySelector('form>div').getBoundingClientRect().height===40);const compact=await dialog.boundingBox();if(width>=768)assert.ok(compact.height<600,'Short desktop details fit their content without a tall empty panel');else {await assertFullscreen();await page.setViewportSize({width:320,height:850});await assertFullscreen();await page.setViewportSize({width,height:850});}await page.screenshot({path:output+'/record-compact-'+width+'.png'});await page.evaluate(()=>window.i50.short(false));await page.waitForFunction(()=>document.querySelector('form>div').getBoundingClientRect().height===1400);if(width<768)await assertFullscreen();const longGeometry=await assertLongLayout();
   const action=dialog.getByRole('button',{name:'Synthetic review',exact:true});assert.equal(await action.evaluate(el=>el.closest('.record-dialog-actions')!==null),true);await action.click();assert.equal(await page.evaluate(()=>window.i50.submits),1,'portal preserves original form owner');
   const geometry=await action.evaluate(el=>{const r=el.getBoundingClientRect();return {top:r.top,bottom:r.bottom,height:r.height,viewport:innerHeight};});assert.ok(geometry.height>=44&&geometry.bottom<=geometry.viewport);await dialog.locator('.request-detail-body').evaluate(el=>el.scrollTop=el.scrollHeight);assert.equal(await action.isVisible(),true);
   const input=dialog.getByLabel('Ghi chú tổng hợp');await input.fill('RETAINED SYNTHETIC EDIT');const handle=await input.elementHandle();await page.evaluate(()=>window.i50.authority(false));assert.equal(await dialog.isVisible(),false);assert.equal(await handle.evaluate(el=>el.isConnected),true);await page.evaluate(()=>window.i50.authority(true));await dialog.waitFor();assert.equal(await input.inputValue(),'RETAINED SYNTHETIC EDIT');
   await dialog.getByRole('button',{name:'Synthetic delete',exact:true}).click();const nested=page.getByRole('alertdialog');await nested.waitFor();await nested.getByRole('button',{name:'Giữ dòng',exact:true}).click();assert.equal(await page.evaluate(()=>window.i50.deletes),0);assert.equal(await input.inputValue(),'RETAINED SYNTHETIC EDIT');
   await dialog.getByRole('button',{name:'Đóng',exact:true}).click();await nested.waitFor();await nested.getByRole('button',{name:'Tiếp tục làm việc',exact:true}).click();assert.equal(await input.inputValue(),'RETAINED SYNTHETIC EDIT');assert.equal(await dialog.isVisible(),true);await page.screenshot({path:output+'/record-'+width+'.png'});results.push({width,status:'PASS',footer:geometry,body:longGeometry});await page.close();
  }
  assert.deepEqual(errors,[]);await writeFile(output+'/evidence.json',JSON.stringify({status:'PASS',results,errors,browser:browser.version(),scope:'synthetic UI only'},null,2)+'\n');
 }finally{await browser?.close();await new Promise(resolve=>server.close(resolve));}
});
