import {test} from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {build} from 'esbuild';import {readFile,mkdir,writeFile} from 'node:fs/promises';
const require=createRequire(import.meta.url),React=require('react'),{renderToStaticMarkup}=require('react-dom/server');
await mkdir('.test-runtime/i50-render',{recursive:true});
await build({stdin:{contents:`export {ScreenHeader} from './components/erp/screen-shell';export {ListLoading} from './components/erp/list-loading';export {RequestListComposition,RequestListPanel,RequestListContent,RequestListTable,RequestListToolbar,RequestSearch,RequestBranch} from './components/erp/request-list-shell';export {RecordDialog,RecordActionBar} from './components/erp/record-dialog';export {RequestHelp} from './components/erp/request-help';export {MobileRequest} from './components/erp/mobile-request';export {MobileInboundRequest} from './components/erp/mobile-inbound-request';export {RequestLoading} from './components/erp/request-presentation';export {ConfiguredDocumentSheet} from './components/erp/configured-screen';export {ReportWorkspace} from './components/erp/reports';export {QueryClient,QueryClientProvider} from '@tanstack/react-query';`,loader:'tsx',resolveDir:process.cwd()},outfile:'.test-runtime/i50-render/ui.cjs',bundle:true,platform:'node',format:'cjs',packages:'external',alias:{'@':process.cwd()},jsx:'automatic',logLevel:'warning'});
const {ScreenHeader,ListLoading,RequestListComposition,RequestListPanel,RequestListContent,RequestListTable,RequestListToolbar,RequestSearch,RequestBranch,RecordDialog,RecordActionBar,MobileRequest,RequestHelp,RequestLoading,ConfiguredDocumentSheet,ReportWorkspace,QueryClient,QueryClientProvider}=require('../.test-runtime/i50-render/ui.cjs'),h=React.createElement;
test('all actual list hosts use shared composition/loading/header and do not expose a scanner or per-screen guide',async()=>{
 for(const name of ['purchase-request-screen','inbound-request-screen','documents']){const source=await readFile(`components/erp/${name}.tsx`,'utf8');assert.match(source,/RequestListComposition/);assert.match(source,/<RequestListPanel\b/);assert.match(source,/<RequestListContent\b/);assert.match(source,/RequestListToolbar/);assert.match(source,/RequestListHeader/);assert.match(source,/RequestLoading/);assert.match(source,/useListControls/);assert.doesNotMatch(source,/RequestQrSearch|TabsTrigger[^>]*value="guide"/);}
 const shell=await readFile('components/erp/workspace.tsx','utf8');assert.match(shell,/<RequestHelp\/>/);assert.match(shell,/<ListViewProvider store={listViews}>/);assert.match(shell,/listViews\.admit\(JSON\.stringify\(\[key,scope\]\)\)/);assert.match(shell,/listViews\.retire\(\)/);assert.match(shell,/setGuideOpen\(true\).*presentationCurrent/);
});
test('real components SSR escape IDs, keep decimal text, show table-shaped verification, and accept only explicit assigned branch locking',()=>{
 const output=renderToStaticMarkup(h(RequestListTable,{label:'QA table',columns:[{id:'id',label:'Mã phiếu'},{id:'quantity',label:'Số lượng'}],rows:[{id:'QA',cells:['QA-<script>','999999999999999999.0001'],action:'Mở',actionLabel:'Mở QA',onOpen:()=>{throw Error('SSR must not invoke Open');}}]}));
 assert.match(output,/data-selectable="false"/);assert.doesNotMatch(output,/role="checkbox"/);assert.match(output,/Tùy chỉnh bảng/);assert.match(output,/999999999999999999\.0001/);assert.match(output,/QA-&lt;script&gt;/);assert.doesNotMatch(output,/<script>/);
 const skeleton=renderToStaticMarkup(h(ListLoading,{label:'Xác minh ERP'}));assert.match(skeleton,/aria-busy="true"/);assert.equal((skeleton.match(/class="skeleton-table-row"/g)??[]).length,6);assert.doesNotMatch(skeleton,/h-24|QA-/);
 const generic=renderToStaticMarkup(h(RequestBranch,{label:'Branch',value:'',branches:[],onChange:()=>{}}));assert.match(generic,/Tất cả/);assert.doesNotMatch(generic,/MB|MN|disabled/);
 const fixed=renderToStaticMarkup(h(RequestBranch,{label:'Branch',value:'',branches:['MB','MN'],assignedBranchId:'MB',onChange:()=>{}}));assert.match(fixed,/disabled=""/);assert.match(fixed,/<option value="MB" selected="">MB/);assert.doesNotMatch(fixed,/Tất cả/);
});
test('retained record shell renders business identity and preserves children while masking; creation grants no implicit action',()=>{
 const masked=renderToStaticMarkup(h(RecordDialog,{open:true,presentationAllowed:false,title:'QA record',documentNumber:'QA-DOC',closeLabel:'Đóng',onRequestClose:()=>{}},h('input',{value:'RETAINED EDIT',readOnly:true})));assert.match(masked,/hidden="" inert=""/);assert.match(masked,/RETAINED EDIT/);
 const fencedActions=renderToStaticMarkup(h(RecordActionBar,{presentationAllowed:false},h("button",null,"PROTECTED ACTION")));assert.match(fencedActions,/hidden="" inert="" aria-hidden="true"/);
 const create=renderToStaticMarkup(h(RecordDialog,{open:true,mode:'create',title:'QA create',closeLabel:'Đóng',onRequestClose:()=>{}},h('p',null,'Không có hợp đồng tạo mới')));assert.match(create,/data-record-mode="create"/);assert.doesNotMatch(create,/Lưu|Xóa|Gửi/);
});
test('synthetic render evidence uses production components and compiled CSS without requests or private data',async()=>{
 const postcss=require('postcss'),tailwind=require('@tailwindcss/postcss');const css=(await postcss([tailwind({base:process.cwd()})]).process(await readFile('app/globals.css','utf8'),{from:process.cwd()+'/app/globals.css'})).css;assert.ok(!css.includes('@import "tailwindcss"'));
 const rows=Array.from({length:6},(_,index)=>({id:`QA-DOC-${index+1}`,cells:[`QA-DOC-${index+1}`,'MB','Chưa có trạng thái'],action:'Mở',actionLabel:`Mở QA-DOC-${index+1}`,onOpen:()=>{}}));
 const list=h(RequestListComposition,null,h(RequestListPanel,null,h(ScreenHeader,{title:'Danh sách chứng từ kiểm thử',description:'Dữ liệu tổng hợp, không kết nối ERP.'}),h(RequestListToolbar,{onSubmit:()=>{}},h(RequestSearch,{label:'Tìm mã',placeholder:'Tìm mã…',value:'',onChange:()=>{}}),h(RequestBranch,{label:'Chi nhánh',value:'',branches:['MB','MN'],onChange:()=>{}}),h('button',{type:'button',className:'request-button'},'Làm mới')),h(RequestListContent,null,h(RequestListTable,{label:'Danh sách kiểm thử',columns:[{id:'id',label:'Mã chứng từ'},{id:'branch',label:'Chi nhánh'},{id:'status',label:'Trạng thái'}],rows}))));
 const content=renderToStaticMarkup(h('main',{className:'workspace-content'},h(ScreenHeader,{level:1,title:'Medcom · Kiểm thử giao diện',description:'SSR thực tế — cần trình duyệt để xác nhận responsive và focus.'}),list,h(ListLoading,{label:'Đang xác minh ERP'}),h(RequestHelp)));
 const html='<!doctype html><html lang="vi"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Medcom I50 synthetic render</title><style>'+css+'</style><body>'+content+'</body></html>';
 assert.doesNotMatch(content,/https?:\/\/(?!www\.w3\.org)/);await writeFile('.test-runtime/i50-render/synthetic-ui.html',html);
 const deniedWrite=async()=>{throw Error('Synthetic SSR must never invoke a service');};
 const initial={documentId:'QA-DOC-ONLY',version:'synthetic',confirmation:'draft',status:{id:'0',label:'Tổng hợp'},values:{purchaseDate:'2026-10-08',personSuggest:'',department:'',purposeId:'',purposeDescOrClient:'',notes:'',branchId:'MB',currencyId:'',objectId:'',lines:[{localKey:'QA-INTERNAL',lineId:'INTERNAL-HIDDEN-ID',itemId:'QA-ITEM',quantity:'',unitPrice:'',budget:'',timeRequired:'',model:''}]}};
 const access={scopeKey:'synthetic-ssr',canRead:true,canEdit:false,canSaveDraft:false,canSubmit:false,available:true,existingOnly:true,branches:[{id:'MB',label:'MB'}],currencies:[],purposes:[],maxNotesLength:2000,maxPurposeLength:2000,maxLines:500,itemLookupId:'synthetic-item',objectLookupId:'synthetic-object'};
 const record=renderToStaticMarkup(h(RecordDialog,{open:true,title:'Đề nghị mua hàng',documentNumber:initial.documentId,closeLabel:'Đóng',onRequestClose:()=>{}},h(MobileRequest,{initial,access,adapter:{execute:deniedWrite,reconcile:deniedWrite,lookup:deniedWrite}})));
 assert.match(record,/QA-ITEM/);assert.doesNotMatch(record,/INTERNAL-HIDDEN-ID/);
 await writeFile('.test-runtime/i50-render/synthetic-record.html','<!doctype html><html lang="vi"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Synthetic readonly record</title><style>'+css+'</style><body>'+record+'</body></html>');await writeFile('.test-runtime/i50-render/render-evidence.json',JSON.stringify({status:'PASS',method:'ReactDOMServer production components + production build CSS',nativeBrowser:'NOT_RUN',responsiveGeometry:'NOT_RUN',focusAndStacking:'NOT_RUN',data:'synthetic only',requests:0},null,2)+'\n');
});

test('actual delete confirmation rejects queued prior targets and revoked authority',async()=>{
 const names=['AlertDialog','AlertDialogContent','AlertDialogHeader','AlertDialogTitle','AlertDialogDescription','AlertDialogFooter','AlertDialogCancel','AlertDialogAction'];
 const primitives="import React from 'react';"+names.map(name=>`export function ${name}({children,...props}){return React.createElement('${name==='AlertDialogAction'||name==='AlertDialogCancel'?'button':'div'}',props,children);}`).join('');
 await build({stdin:{contents:"export {RecordDeleteConfirmation} from './components/erp/record-delete-confirmation';",loader:'tsx',resolveDir:process.cwd()},outfile:'.test-runtime/i50-render/delete-test.cjs',bundle:true,platform:'node',format:'cjs',packages:'external',alias:{'@':process.cwd()},jsx:'automatic',logLevel:'warning',plugins:[{name:'DOM-only-modal-primitives',setup(build){build.onLoad({filter:/components[\\/]ui[\\/]alert-dialog\.tsx$/},()=>({contents:primitives,loader:'jsx'}));}}]});
 const {RecordDeleteConfirmation}=require('../.test-runtime/i50-render/delete-test.cjs'),{act,create}=require('react-test-renderer');globalThis.IS_REACT_ACT_ENVIRONMENT=true;
 const first={},second={};let confirmed=0,allowed=true,tree;const render=intent=>h(RecordDeleteConfirmation,{open:true,intent,identity:'Dòng 1 · QA-ITEM',presentationAllowed:allowed,isAllowed:()=>allowed,onCancel:()=>{},onConfirm:()=>{confirmed++;}});
 try{await act(async()=>{tree=create(render(first));});const action=()=>tree.root.findAllByType('button').find(button=>button.children.includes('Xóa dòng'));const queued=action().props.onClick;await act(async()=>tree.update(render(second)));await act(async()=>queued());assert.equal(confirmed,0,'old local removal target cannot become the new target');await act(async()=>action().props.onClick());assert.equal(confirmed,1);const current=action().props.onClick;allowed=false;await act(async()=>tree.update(render(second)));await act(async()=>current());assert.equal(confirmed,1,'authority loss fences an already queued confirmation');allowed=true;await act(async()=>tree.update(render(second)));await act(async()=>current());assert.equal(confirmed,1,'Same-target presentation restoration cannot revive a queued old confirmation');await act(async()=>action().props.onClick());assert.equal(confirmed,2,'Fresh current confirmation remains actionable');}finally{await act(async()=>tree?.unmount());}
});


test('shared LIST panel leaves viewport sticky ancestry visible and clips only sibling content (static/SSR, not native scroll)',async()=>{
 const html=renderToStaticMarkup(h(RequestListComposition,null,h(RequestListPanel,{className:'caller-panel'},h(RequestListToolbar,null,h('input',{readOnly:true})),h(RequestListContent,null,h('div',null,'SYNTHETIC CONTENT')))));
 assert.match(html,/data-list-panel=""[^>]*class="[^"]*request-list-panel/);assert.match(html,/data-list-content=""[^>]*class="request-list-content/);assert.equal((html.match(/request-list-panel/g)??[]).length,1);
 const css=require('postcss').parse(await readFile('app/globals.css','utf8'));const declarations=selector=>{const found={};css.walkRules(selector,rule=>{rule.walkDecls(decl=>{found[decl.prop]=decl.value;});});return found;};
 assert.equal(declarations('.request-list-panel').overflow,'visible');assert.equal(declarations('.request-list-content').overflow,'hidden');assert.equal(declarations('.request-panel').overflow,'hidden','Generic panels and modal clipping are not globally relaxed');assert.equal(declarations('.document-panel').overflow,undefined,'No orders-only overflow escape remains');assert.equal(declarations('.request-list-toolbar').position,'sticky');
 await writeFile('.test-runtime/i50-render/list-panel-contract.json',JSON.stringify({status:'PASS',method:'actual components SSR + PostCSS source declarations',nativeScroll:'NOT_RUN',listPanel:'overflow:visible',innerContent:'overflow:hidden',genericPanelClipping:'preserved',screens:['purchase-requests','purchase-orders','inbound-requests']},null,2)+'\n');
});

test('approved configured/report loading hosts reach shared form/list geometry without transport (actual SSR)',async()=>{
 const blocked=async()=>{assert.fail('Synthetic SSR must not dispatch service calls');};const client=new QueryClient({defaultOptions:{queries:{retry:false}}});
 const workspace={session:{tenantId:'QA-T',companyId:'QA-C',authorityVersion:1,capabilities:['purchase-orders.read']},sessionScope:'QA-SESSION',readScope:'QA-READ',branchIds:['QA-BRANCH'],navigation:[]};
 const wrapped=node=>renderToStaticMarkup(h(QueryClientProvider,{client},node));
 try{
  const form=renderToStaticMarkup(h(RequestLoading,{form:true,label:'Synthetic form verification'}));assert.match(form,/form-skeleton/);assert.equal((form.match(/class="skeleton-fields"/g)??[]).length,1);assert.doesNotMatch(form,/skeleton-table-row/);
  const configured=wrapped(h(ConfiguredDocumentSheet,{screen:'purchase-orders',workspace,extension:{load:blocked},documentId:'QA-DOC',selected:null,close:()=>{},onDenied:()=>{}}));assert.match(configured,/aria-label="Đang xác minh chứng từ"/);assert.match(configured,/form-skeleton/);assert.doesNotMatch(configured,/h-60/);
  const reports=wrapped(h(ReportWorkspace,{adapter:{catalog:blocked,jobs:blocked,start:blocked,reconcileStart:blocked,download:blocked},lookupAdapter:blocked,scopeKey:'synthetic-ssr',onDenied:()=>{}}));assert.equal((reports.match(/aria-busy="true"/g)??[]).length,3);assert.match(reports,/form-skeleton/);assert.equal((reports.match(/class="skeleton-table-row"/g)??[]).length,12);
  const inboundSource=await readFile('components/erp/mobile-inbound-request.tsx','utf8');assert.match(inboundSource,/state\.phase==="loading"&&!unresolved&&!state\.awaitingSnapshot&&<RequestLoading form/);assert.match(inboundSource,/state\.awaitingSnapshot&&<p role="alert">/);assert.match(inboundSource,/unresolved&&<div><p>Yêu cầu gốc:/);
 }finally{client.clear();}
});

test('shared dialog exposes its actual scroll owner and orders bind guarded capture/restoration there (SSR/source, not native scroll)',async()=>{
 const bodyRef=React.createRef();const html=renderToStaticMarkup(h(RecordDialog,{open:true,title:'Synthetic order',closeLabel:'Đóng',onRequestClose:()=>{},bodyRef,onBodyScroll:()=>{}},h('div',{className:'detail-body'},'QA-CONTENT')));assert.match(html,/class="request-detail-body"><div class="detail-body"/);
 const source=await readFile('components/erp/workspace.tsx','utf8');assert.match(source,/<RecordDialog bodyRef={detailViewport} onBodyScroll=/);assert.match(source,/if\(presentationAllowed&&read\.active&&detail\)scroll\.current=event\.currentTarget\.scrollTop/);assert.match(source,/if\(presentationAllowed&&read\.active&&detail&&detailViewport\.current\)detailViewport\.current\.scrollTop=scroll\.current/);assert.doesNotMatch(source,/<div ref={detailViewport} className="detail-body"/);
});
