import {mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import ts from 'typescript';import {spawnSync} from 'node:child_process';
import {build} from 'esbuild';
if(process.argv.slice(2).some(argument=>argument!=='--contracts-only'))throw Error('Unknown ERP test argument');
const output='.test-runtime/erp-tests';mkdirSync(output,{recursive:true});
for(const name of ['contracts','catalog','navigation','api','presentation','ui-contracts','proxy-policy','proxy']){let source=readFileSync(`lib/erp/${name}.ts`,'utf8');source=source.replaceAll('from "./contracts"','from "./contracts.js"').replaceAll('from "./catalog"','from "./catalog.js"').replaceAll('from "./proxy-policy"','from "./proxy-policy.js"');writeFileSync(`${output}/${name}.js`,ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText);}
await build({stdin:{contents:'export {ErpGrid} from "./components/erp/grid"; export {DocumentEditor} from "./components/erp/document-editor"; export {RoleNavigationEditor} from "./components/erp/role-navigation-editor"; export {ErrorPanel} from "./components/erp/feedback"; export {ApiError} from "./lib/erp/api";',resolveDir:process.cwd(),loader:'tsx'},outfile:`${output}/ui-components.js`,bundle:true,platform:'node',format:'esm',packages:'external',alias:{'@':process.cwd()},jsx:'automatic',logLevel:'warning'});
const r=spawnSync(process.execPath,['--experimental-strip-types','--test','tests/proxy-policy.test.ts','tests/api.test.mjs','tests/document-status.test.mjs','tests/proxy.test.mjs','tests/navigation.test.mjs','tests/presentation.test.mjs','tests/components.test.mjs','tests/runtime-config.test.mjs','tests/standalone-package.test.mjs','tests/mobile-request.test.mjs','tests/qr-scanner.test.mjs','tests/warehouse-qr.test.mjs','tests/purchase-request-integration.test.mjs','tests/purchase-request-lookup.test.mjs','tests/workspace-auth-gate.test.mjs','tests/request-qr-search.test.mjs','tests/purchase-reference-context.test.mjs','tests/request-screen-controls.test.mjs','tests/configured-authority.test.mjs'],{stdio:'inherit'});if(r.error)throw r.error;if(r.status!==0)process.exit(r.status??1);
// The default aggregate includes real browser gates. CI runs the exact same
// required runner in its dedicated step after the existing required UI suites.
if(!process.argv.includes('--contracts-only')){const browser=spawnSync(process.execPath,['tests/required-ui-gates.mjs'],{stdio:'inherit'});if(browser.error)throw browser.error;process.exit(browser.status??1);}
